"""
models/diffusivity_workflow.py
================================
Public functions that back the action cells of calculation/diffusivity.ipynb.

All configuration variables (input_structures, temperatures, …) remain in the
notebook. Cells import one function each and call it with those variables.
"""

from __future__ import annotations

import os
import textwrap

import numpy as np
import pandas as pd

try:
    from IPython.display import display as _display
except ImportError:
    _display = print


# ─────────────────────────────────────────────────────────────────────────────
# Cell e27b171d — Generate diffusivity_run.py
# ─────────────────────────────────────────────────────────────────────────────

def generate_diffusivity_scripts(
    input_structures,
    n_h_values,
    temperatures,
    work_dir,
    nvt_wall_time,
    cutoff,
    gpu_partition,
    gpu_time,
    timestep_ps,
    tau_t_ps,
    n_equil_steps,
    n_prod_steps,
    thermo_every,
    dump_every,
    velocity_seed,
    restart_every,
    short_gpu_partition='sharing',
    short_gpu_time='00:20:00',
    short_gpu_cutoff=None,
    npt_gpu_partition='gpu',
    npt_gpu_time='08:00:00',
    npt_gpu_cutoff=None,
    npt_heat_steps=20000,
    npt_prod_steps=200000,
    npt_baro_damp=1.0,
    npt_dump_every=100,
    min_etol=0.0,
    min_ftol=1e-8,
    min_maxiter=50000,
    min_maxeval=500000,
    metal_table: dict | None = None,
    out_py: str = '',
) -> str:
    """Write diffusivity_run.py with embedded config. Returns the output path."""
    if metal_table is None:
        metal_table = {}
    if short_gpu_cutoff is None:
        _h, _m, _s = map(int, short_gpu_time.split(':'))
        _tot = _h * 3600 + _m * 60 + _s - 300
        short_gpu_cutoff_val = f'{_tot//3600:02d}:{(_tot%3600)//60:02d}:{_tot%60:02d}'
    else:
        short_gpu_cutoff_val = short_gpu_cutoff
    if npt_gpu_cutoff is None:
        _h, _m, _s = map(int, npt_gpu_time.split(':'))
        _tot = _h * 3600 + _m * 60 + _s - 300
        npt_gpu_cutoff_val = f'{_tot//3600:02d}:{(_tot%3600)//60:02d}:{_tot%60:02d}'
    else:
        npt_gpu_cutoff_val = npt_gpu_cutoff

    _header = f'''#!/usr/bin/env python3
"""
diffusivity_run.py
==================
Standalone H-diffusivity workflow orchestrator.
Submitted via diffusivity_run.sh (configured by notebook variables).

Loop: input_structures × n_h_values × temperatures
  Phase 1a: Minimise input bulk structure
  Phase 1b: NPT MD at each T → a0(T) → insert H → minimise bulk+H
  Phase 2 : NVT MD (chained SLURM GPU jobs, one per temperature)
  Phase 3 : MSD  →  D(T)  →  Arrhenius fit

Generated by calculation/diffusivity.ipynb — do not edit by hand.
"""

# ── config (injected by diffusivity.ipynb) ────────────────────────────────────
INPUT_STRUCTURES = {input_structures!r}
N_H_VALUES       = {n_h_values!r}
TEMPERATURES     = {temperatures!r}
WORK_DIR         = {work_dir!r}
NVT_WALL_TIME    = {nvt_wall_time!r}
CUTOFF           = {cutoff!r}
GPU_PARTITION        = {gpu_partition!r}
GPU_TIME             = {gpu_time!r}
SHORT_GPU_PARTITION  = {short_gpu_partition!r}
SHORT_GPU_TIME       = {short_gpu_time!r}
SHORT_GPU_CUTOFF     = {short_gpu_cutoff_val!r}
NPT_GPU_PARTITION    = {npt_gpu_partition!r}
NPT_GPU_TIME         = {npt_gpu_time!r}
NPT_GPU_CUTOFF       = {npt_gpu_cutoff_val!r}
# MD defaults (ps units)
TIMESTEP_PS      = {timestep_ps!r}
TAU_T_PS         = {tau_t_ps!r}
N_EQUIL_STEPS    = {n_equil_steps!r}
N_PROD_STEPS     = {n_prod_steps!r}
THERMO_EVERY     = {thermo_every!r}
DUMP_EVERY       = {dump_every!r}
VELOCITY_SEED    = {velocity_seed!r}
RESTART_EVERY    = {restart_every!r}
# NPT Phase 1b
NPT_HEAT_STEPS   = {npt_heat_steps!r}
NPT_PROD_STEPS   = {npt_prod_steps!r}
NPT_BARO_DAMP    = {npt_baro_damp!r}
NPT_DUMP_EVERY   = {npt_dump_every!r}
# Minimisation (Phase 1a / Phase 1b bulk+H)
MIN_ETOL         = {min_etol!r}
MIN_FTOL         = {min_ftol!r}
MIN_MAXITER      = {min_maxiter!r}
MIN_MAXEVAL      = {min_maxeval!r}
# Element / type tables per metal stem (oxide vs non-oxide)
METAL_TABLE      = {metal_table!r}

'''

    _body = r"""
import os
import sys
import json as _json_lat
sys.path.insert(0, os.path.dirname(WORK_DIR))

from models.config import (
    LAMMPS_CMD, MACE_MODEL_LAMMPS, KOKKOS_FLAGS,
    PAIR_STYLE, PAIR_SUFFIX,
    E2T_7, MASSES_7, ELEM_STR_7,
    SLURM_DEFAULTS,
)
from models.structure import get_lattice_parameter_from_dump, insert_hydrogen
from models.utils import make_run_dirs
from models.lammps_script import (
    write_minimization_script,
    write_npt_script,
    write_npt_restart_script,
    write_nvt_bulk_script,
    write_nvt_equil_restart_script,
    write_nvt_prod_restart_script,
)
from models.create_slurm import (
    write_slurm_job,
    write_chained_slurm_job,
    submit_slurm_job,
    submit_with_retry,
    wait_for_jobs,
)
from models.diffusivity_post_processing import (
    run_diffusivity_pipeline,
    save_diffusivity_table,
    run_arrhenius_pipeline,
)
from models.checkpoint import is_done, mark_done

GPU_SLURM_CFG       = dict(SLURM_DEFAULTS, partition=GPU_PARTITION,      time=NVT_WALL_TIME)
SHORT_GPU_SLURM_CFG = dict(SLURM_DEFAULTS, partition=SHORT_GPU_PARTITION, time=SHORT_GPU_TIME)
# NPT is real chained MD (heat+prod, self-resubmitting) -- same category as
# NVT above, not a quick one-shot minimization like bare-bulk/bulk+H min
# (which stay on SHORT_GPU_SLURM_CFG).
NPT_GPU_SLURM_CFG   = dict(SLURM_DEFAULTS, partition=NPT_GPU_PARTITION,   time=NPT_GPU_TIME)
KK = ' '.join(KOKKOS_FLAGS)


def _require_file(path, hint):
    # Fail fast with a clear message when a SLURM job's output is missing.
    # wait_for_jobs only waits for jobs to leave the queue — a crashed LAMMPS
    # job looks identical to a successful one, so each phase must verify its
    # output exists before the next phase consumes it.
    if not os.path.exists(path):
        raise RuntimeError(
            f'Expected output missing: {path}\n'
            f'  The SLURM job that should have written it likely failed. {hint}'
        )

_FAILURES = []

# ── main loop ─────────────────────────────────────────────────────────────────
for struct_path in INPUT_STRUCTURES:
    struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
    _cfg      = METAL_TABLE.get(struct_stem, {})
    _ELEM_STR = _cfg.get('elem_str', ELEM_STR_7)
    _E2T      = _cfg.get('e2t',      E2T_7)
    _MASSES   = _cfg.get('masses',   MASSES_7)

    # ── Shared, n_H-independent: Phase 1a (bare-bulk min) + Phase 1b Step A
    # (NPT) ── Both happen before any H is inserted, so they must run once
    # per structure, not once per (structure, n_H) -- previously each was
    # redone once per n_H (see GitHub issue on redundant NPT/minimisation
    # per H-concentration). min_bare_out reuses pipeline.ipynb's
    # pre-pipeline bulk_min_{stem}.lammps if it already exists.
    try:
        print(f'\n{"="*60}')
        print(f'  Structure : {struct_stem}   (shared bare-bulk + NPT, all n_H)')
        print(f'{"="*60}')

        _shared_dirs = make_run_dirs(
            name=struct_stem,
            temperatures=TEMPERATURES,
            base_dir=os.path.join(WORK_DIR, 'results'),
        )
        shared_lmp_dir = os.path.join(_shared_dirs['root'], 'lammps_scripts')
        shared_sh_dir  = os.path.join(_shared_dirs['root'], 'slurm_scripts')
        os.makedirs(shared_lmp_dir, exist_ok=True)
        os.makedirs(shared_sh_dir,  exist_ok=True)

        # ── Phase 1a ─────────────────────────────────────────────────────────
        print('\n--- Phase 1a: Minimise bare bulk ---')

        min_bare_lmp = os.path.join(shared_lmp_dir, 'minimize_bare.lammps')
        min_bare_out = os.path.join(WORK_DIR, 'structures', f'bulk_min_{struct_stem}.lammps')
        min_bare_sh  = os.path.join(shared_sh_dir,  'minimize_bare.sh')
        os.makedirs(os.path.dirname(min_bare_out), exist_ok=True)
        _phase1a_done_marker = os.path.join(_shared_dirs['root'], 'phase1a.done')

        if not os.path.exists(min_bare_out):
            write_minimization_script(
                bulk_input=struct_path,
                min_output=min_bare_out,
                out_path=min_bare_lmp,
                pair_style=PAIR_STYLE,
                mace_model=MACE_MODEL_LAMMPS,
                pair_suffix=PAIR_SUFFIX,
                elem_str=_ELEM_STR,
                etol=MIN_ETOL,
                ftol=MIN_FTOL,
                maxiter=MIN_MAXITER,
                maxeval=MIN_MAXEVAL,
            )
            write_slurm_job(
                job_name=f'min_bare_{struct_stem}',
                slurm_config=SHORT_GPU_SLURM_CFG,
                out_path=min_bare_sh,
                runner='lmp',
                lammps_cmd=LAMMPS_CMD,
                kokkos_flags=KOKKOS_FLAGS,
                script_path=min_bare_lmp,
            )
            jid = submit_with_retry(min_bare_sh)
            wait_for_jobs({'min_bare': jid})
            _require_file(min_bare_out,
                          f'Check the min_bare job log in {shared_sh_dir}.')
            mark_done(_phase1a_done_marker)
            print(f'  [1a] Bare bulk minimisation done.  Output → {min_bare_out}')
        else:
            mark_done(_phase1a_done_marker)
            print(f'  [1a] Already exists: {min_bare_out} — skipping '
                  f'(reused from the pre-pipeline step or a prior n_H run)')

        # ── Phase 1b — Step A: NPT at every T in parallel ────────────────────
        print('\n--- Phase 1b: NPT equilibration at each temperature ---')

        npt_job_ids     = {}
        npt_final_paths = {}
        npt_stem = os.path.splitext(min_bare_out)[0]

        for T in TEMPERATURES:
            npt_lmp  = os.path.join(shared_lmp_dir, f'npt_{T}K.lammps')
            npt_dump = os.path.join(_shared_dirs['structures'], f'npt_boxdims_{T}K.dat')
            npt_sh   = os.path.join(shared_sh_dir,  f'npt_{T}K.sh')
            npt_final_paths[T] = f'{npt_stem}_npt_final_{T}K.lammps'

            npt_rst_lmp          = os.path.join(shared_lmp_dir, f'npt_restart_{T}K.lammps')
            npt_after_heat_rst   = f'{os.path.splitext(npt_dump)[0]}_after_heat.restart'
            npt_done_marker      = os.path.join(_shared_dirs['root'], f'npt_{T}K.done')

            if not os.path.exists(npt_final_paths[T]):
                write_npt_script(
                    min_output=min_bare_out,
                    npt_dump=npt_dump,
                    out_path=npt_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=_ELEM_STR,
                    target_t=T,
                    timestep=TIMESTEP_PS,
                    thermo_damp=TAU_T_PS,
                    baro_damp=NPT_BARO_DAMP,
                    heat_steps=NPT_HEAT_STEPS,
                    npt_steps=NPT_PROD_STEPS,
                    dump_every=NPT_DUMP_EVERY,
                )
                write_npt_restart_script(
                    restart_file=npt_after_heat_rst,
                    npt_dump=npt_dump,
                    min_output=min_bare_out,
                    out_path=npt_rst_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=_ELEM_STR,
                    target_t=T,
                    timestep=TIMESTEP_PS,
                    thermo_damp=TAU_T_PS,
                    baro_damp=NPT_BARO_DAMP,
                    npt_steps=NPT_PROD_STEPS,
                    dump_every=NPT_DUMP_EVERY,
                )
                write_chained_slurm_job(
                    job_name=f'npt_{T}K_{struct_stem}',
                    slurm_config=NPT_GPU_SLURM_CFG,
                    out_path=npt_sh,
                    first_commands=[f'{LAMMPS_CMD} {KK} -in {npt_lmp}'],
                    restart_commands=[f'{LAMMPS_CMD} {KK} -in {npt_rst_lmp}'],
                    restart_glob=npt_after_heat_rst,
                    cutoff=NPT_GPU_CUTOFF,
                    work_dir=WORK_DIR,
                )
                npt_job_ids[f'npt_{T}K'] = submit_with_retry(npt_sh)
                print(f'  Submitted NPT {T}K  →  job {npt_job_ids[f"npt_{T}K"]}')
            else:
                mark_done(npt_done_marker)
                print(f'  [1b] NPT {T}K already done — skipping')

        print(f'  Waiting for {len(npt_job_ids)} NPT jobs ...')
        wait_for_jobs(npt_job_ids)
        _a0_by_T = {}   # collect a0(T) in Å for each temperature -- shared across all n_H
        for T in TEMPERATURES:
            _require_file(npt_final_paths[T],
                          f'Check the npt_{T}K job log in {shared_sh_dir}.')
            _npt_dump_T = os.path.join(_shared_dirs['structures'], f'npt_boxdims_{T}K.dat')
            _require_file(_npt_dump_T,
                          f'Check the npt_{T}K job log in {shared_sh_dir}.')
            mark_done(os.path.join(_shared_dirs['root'], f'npt_{T}K.done'))
            _a0_by_T[T] = get_lattice_parameter_from_dump(_npt_dump_T, n_last=50)
            print(f'  [1b] T={T}K  a0 = {_a0_by_T[T]:.4f} Å')
        print('  All NPT jobs done.')

        # Save temperature-dependent lattice parameters for Part 2 (permeation_run.py)
        _lat_out = os.path.join(WORK_DIR, 'results', struct_stem, 'lattice_params_vs_T.json')
        os.makedirs(os.path.dirname(_lat_out), exist_ok=True)
        with open(_lat_out, 'w') as _f:
            _json_lat.dump({'temperatures': list(_a0_by_T.keys()),
                            'a0_m': [v * 1e-10 for v in _a0_by_T.values()]}, _f, indent=2)
        print(f'  Saved lattice_params_vs_T.json → {_lat_out}')
    except Exception as _exc:
        print(f'\n  *** FAILED (shared bare-bulk/NPT for {struct_stem}): {_exc} ***')
        print(f'  Skipping all n_H values for {struct_stem}; continuing with next structure.')
        for _n_h in N_H_VALUES:
            _FAILURES.append({'run_name': f'{struct_stem}_{_n_h}H', 'struct': struct_stem,
                               'n_h': _n_h, 'error': str(_exc)})
        continue

    for n_h in N_H_VALUES:
        run_name = f'{struct_stem}_{n_h}H'
        try:
            print(f'\n{"="*60}')
            print(f'  Structure : {struct_stem}   n_H : {n_h}')
            print(f'{"="*60}')

            dirs = make_run_dirs(
                name=run_name,
                temperatures=TEMPERATURES,
                base_dir=os.path.join(WORK_DIR, 'results'),
            )

            phase1_lmp_dir = os.path.join(dirs['root'], 'lammps_scripts')
            phase1_sh_dir  = os.path.join(dirs['root'], 'slurm_scripts')
            os.makedirs(phase1_lmp_dir, exist_ok=True)
            os.makedirs(phase1_sh_dir,  exist_ok=True)

            # ── Phase 1b — Step B: insert H at a0(T), minimise ───────────────────
            print('\n--- Phase 1b (cont.): Insert H and minimise at each temperature ---')

            min_h_job_ids = {}
            T_to_bulk_h   = {}

            for T in TEMPERATURES:
                a0_T = _a0_by_T[T]

                min_h_lmp_T = os.path.join(phase1_lmp_dir, f'minimize_h_{T}K.lammps')
                min_h_out_T = os.path.join(dirs['structures'], f'{T}K', 'bulk_min_h.lammps')
                min_h_sh_T  = os.path.join(phase1_sh_dir,  f'minimize_h_{T}K.sh')
                T_to_bulk_h[T] = min_h_out_T
                min_h_done_marker = os.path.join(dirs['structures'], f'{T}K', 'minh.done')

                if not os.path.exists(min_h_out_T):
                    bulk_h_path_T, _h_pos_T, _min_hm_T = insert_hydrogen(
                        bulk_min_path=npt_final_paths[T],
                        n_h=n_h,
                        masses=_MASSES,
                        e2t=_E2T,
                        out_dir=os.path.join(dirs['structures'], f'{T}K'),
                        a0=a0_T,
                    )
                    print(f'  [1b] T={T}K  inserted {n_h} H  min_H-metal={_min_hm_T:.3f} Å  → {bulk_h_path_T}')
                    write_minimization_script(
                        bulk_input=bulk_h_path_T,
                        min_output=min_h_out_T,
                        out_path=min_h_lmp_T,
                        pair_style=PAIR_STYLE,
                        mace_model=MACE_MODEL_LAMMPS,
                        pair_suffix=PAIR_SUFFIX,
                        elem_str=_ELEM_STR,
                        etol=MIN_ETOL,
                        ftol=MIN_FTOL,
                        maxiter=MIN_MAXITER,
                        maxeval=MIN_MAXEVAL,
                    )
                    write_slurm_job(
                        job_name=f'min_h_{T}K_{run_name}',
                        slurm_config=SHORT_GPU_SLURM_CFG,
                        out_path=min_h_sh_T,
                        runner='lmp',
                        lammps_cmd=LAMMPS_CMD,
                        kokkos_flags=KOKKOS_FLAGS,
                        script_path=min_h_lmp_T,
                    )
                    min_h_job_ids[f'min_h_{T}K'] = submit_with_retry(min_h_sh_T)
                else:
                    mark_done(min_h_done_marker)
                    print(f'  [1b] bulk+H min {T}K already done — skipping')

            print(f'  Waiting for {len(min_h_job_ids)} bulk+H minimisation jobs ...')
            wait_for_jobs(min_h_job_ids)
            for T in TEMPERATURES:
                _require_file(T_to_bulk_h[T],
                              f'Check the min_h_{T}K job log in {phase1_sh_dir}.')
                mark_done(os.path.join(dirs['structures'], f'{T}K', 'minh.done'))
            print('  All bulk+H minimisations done.')

            # Save temperature-dependent lattice parameters for Part 2 (permeation_run.py)
            _lat_out = os.path.join(WORK_DIR, 'results', struct_stem, 'lattice_params_vs_T.json')
            os.makedirs(os.path.dirname(_lat_out), exist_ok=True)
            with open(_lat_out, 'w') as _f:
                _json_lat.dump({'temperatures': list(_a0_by_T.keys()),
                                'a0_m': [v * 1e-10 for v in _a0_by_T.values()]}, _f, indent=2)
            print(f'  Saved lattice_params_vs_T.json → {_lat_out}')

            # ── Phase 2 ──────────────────────────────────────────────────────────
            print('\n--- Phase 2: NVT MD ---')
            chain_sh_by_T = {}

            for T in TEMPERATURES:
                lmp_dir = dirs[T]['lammps_scripts']
                sh_dir  = dirs[T]['slurm_scripts']
                res_dir = dirs[T]['results']
                rst_dir = os.path.join(res_dir, 'checkpoints')
                os.makedirs(rst_dir, exist_ok=True)

                nvt_lmp           = os.path.join(lmp_dir, f'nvt_{T}K.lammps')
                nvt_equil_rst_lmp = os.path.join(lmp_dir, f'nvt_{T}K_rst_equil.lammps')
                nvt_prod_rst_lmp  = os.path.join(lmp_dir, f'nvt_{T}K_rst_prod.lammps')
                traj_file         = os.path.join(res_dir, f'nvt_{T}K.dump')
                out_file          = os.path.join(res_dir, f'nvt_{T}K.out')
                log_file          = os.path.join(res_dir, f'nvt_{T}K.log')
                msd_equil_file    = os.path.join(res_dir, f'msd_{T}K_equil.dat')
                msd_prod_file     = os.path.join(res_dir, f'msd_{T}K_prod.dat')
                rst_glob          = os.path.join(rst_dir, f'nvt_{T}K.*.restart')
                chain_sh          = os.path.join(sh_dir,  f'nvt_{T}K_chain.sh')
                chain_sh_by_T[T]  = chain_sh

                if not is_done(chain_sh + '.done'):
                    write_nvt_bulk_script(
                        bulk_h_file=T_to_bulk_h[T],
                        traj_file=traj_file,
                        out_file=out_file,
                        msd_equil_file=msd_equil_file,
                        msd_prod_file=msd_prod_file,
                        out_path=nvt_lmp,
                        pair_style=PAIR_STYLE,
                        mace_model=MACE_MODEL_LAMMPS,
                        pair_suffix=PAIR_SUFFIX,
                        elem_str=_ELEM_STR,
                        temperature=T,
                        h_type=_E2T['H'],
                        timestep=TIMESTEP_PS,
                        tau_t=TAU_T_PS,
                        n_equil=N_EQUIL_STEPS,
                        n_prod=N_PROD_STEPS,
                        thermo_every=THERMO_EVERY,
                        dump_every=DUMP_EVERY,
                        velocity_seed=VELOCITY_SEED,
                        restart_dir=rst_dir,
                        restart_every=RESTART_EVERY,
                    )
                    write_nvt_equil_restart_script(
                        restart_file=rst_glob,
                        traj_file=traj_file,
                        out_file=out_file,
                        msd_equil_file=msd_equil_file,
                        msd_prod_file=msd_prod_file,
                        log_file=log_file,
                        out_path=nvt_equil_rst_lmp,
                        pair_style=PAIR_STYLE,
                        mace_model=MACE_MODEL_LAMMPS,
                        pair_suffix=PAIR_SUFFIX,
                        elem_str=_ELEM_STR,
                        temperature=T,
                        h_type=_E2T['H'],
                        timestep=TIMESTEP_PS,
                        tau_t=TAU_T_PS,
                        n_equil=N_EQUIL_STEPS,
                        n_prod=N_PROD_STEPS,
                        thermo_every=THERMO_EVERY,
                        dump_every=DUMP_EVERY,
                        restart_dir=rst_dir,
                        restart_every=RESTART_EVERY,
                    )
                    write_nvt_prod_restart_script(
                        restart_file=rst_glob,
                        traj_file=traj_file,
                        out_file=out_file,
                        msd_prod_file=msd_prod_file,
                        log_file=log_file,
                        out_path=nvt_prod_rst_lmp,
                        pair_style=PAIR_STYLE,
                        mace_model=MACE_MODEL_LAMMPS,
                        pair_suffix=PAIR_SUFFIX,
                        elem_str=_ELEM_STR,
                        temperature=T,
                        h_type=_E2T['H'],
                        timestep=TIMESTEP_PS,
                        tau_t=TAU_T_PS,
                        n_equil=N_EQUIL_STEPS,
                        n_prod=N_PROD_STEPS,
                        thermo_every=THERMO_EVERY,
                        dump_every=DUMP_EVERY,
                        restart_dir=rst_dir,
                        restart_every=RESTART_EVERY,
                    )
                    write_chained_slurm_job(
                        job_name=f'nvt_{T}K_{run_name}',
                        slurm_config=GPU_SLURM_CFG,
                        out_path=chain_sh,
                        first_commands=[
                            f'{LAMMPS_CMD} {KK} -in {nvt_lmp} -log {log_file}',
                        ],
                        equil_restart_commands=[
                            f'{LAMMPS_CMD} {KK} -in {nvt_equil_rst_lmp} -log /dev/null',
                        ],
                        prod_restart_commands=[
                            f'{LAMMPS_CMD} {KK} -in {nvt_prod_rst_lmp} -log /dev/null',
                        ],
                        n_equil=N_EQUIL_STEPS,
                        restart_glob=rst_glob,
                        cutoff=CUTOFF,
                        work_dir=WORK_DIR,
                    )
                    # Stale failure sentinel from an earlier attempt would make the
                    # polling loop below abort before the new job even starts.
                    if os.path.exists(chain_sh + '.failed'):
                        os.remove(chain_sh + '.failed')
                    job_id = submit_with_retry(chain_sh)
                    print(f'  [2] Submitted NVT {T}K  →  job {job_id}')
                else:
                    print(f'  [2] NVT {T}K already done — skipping')

            print('  Waiting for NVT jobs (polling .done sentinels) ...')
            import time as _time
            pending = set(TEMPERATURES)
            while pending:
                for T in list(pending):
                    if is_done(chain_sh_by_T[T] + '.done'):
                        pending.discard(T)
                        print(f'  NVT {T}K complete')
                    elif os.path.exists(chain_sh_by_T[T] + '.failed'):
                        raise RuntimeError(
                            f'NVT {T}K chain job failed (sentinel: '
                            f'{chain_sh_by_T[T]}.failed). Check the chain job '
                            f'logs next to that script. Aborting instead of '
                            f'polling forever.'
                        )
                if pending:
                    _time.sleep(60)
            print('  All NVT jobs done.')

            # ── Phase 3 ──────────────────────────────────────────────────────────
            print('\n--- Phase 3: Post-processing ---')
            analysis_dir = os.path.join(dirs['root'], 'analysis')
            os.makedirs(analysis_dir, exist_ok=True)
            _arr_out = os.path.join(dirs['root'], 'diffusivity_arrhenius.json')
            _phase3_done_marker = os.path.join(analysis_dir, 'phase3.done')

            if is_done(_phase3_done_marker) and os.path.exists(_arr_out):
                print(f'  [3] Already done: {_arr_out} — skipping')
            else:
                D_vals, D_errs, R2_vals = [], [], []
                for T in TEMPERATURES:
                    dump   = os.path.join(dirs[T]['results'], f'nvt_{T}K.dump')
                    result = run_diffusivity_pipeline(
                        dump_file=dump,
                        temperature=T,
                        h_type=_E2T['H'],
                        outdir=analysis_dir,
                    )
                    D_vals.append(result['D'])
                    D_errs.append(result['sigma_D'])
                    R2_vals.append(result['R2'])
                    print(f'  T={T}K   D={result["D"]:.4e} m2/s   R2={result["R2"]:.4f}')

                table_path = os.path.join(analysis_dir, 'diffusivity_table.txt')
                save_diffusivity_table(TEMPERATURES, D_vals, D_errs, R2_vals, table_path)

                print(f'  D(T) summary: {" | ".join(f"{T:.0f}K:{D:.2e}" for T, D in zip(TEMPERATURES, D_vals))}')
                arr = run_arrhenius_pipeline(
                    diffusivity_file=table_path,
                    outdir=analysis_dir,
                )
                print(f'  Arrhenius: Ea={arr["Ea"]:.4f} eV  D0={arr["D0"]:.4e} m²/s  R²={arr["R2"]:.4f}')

                # Save Arrhenius params so Part 2 (permeation_run.py) can load them.
                # Per (stem, n_h) — NOT shared across H-concentrations, since D0/Ea
                # genuinely differ with H loading (see GitHub issue on the overwrite bug).
                os.makedirs(os.path.dirname(_arr_out), exist_ok=True)
                with open(_arr_out, 'w') as _f:
                    _json_lat.dump({
                        'D0_m2s':     arr['D0'],
                        'E_D_eV':     arr['Ea'],
                        'D0_err':     arr['D0_err'],
                        'E_D_err_eV': arr['Ea_err'],
                        'R2_fit':     arr['R2'],
                        'T_K_arr':    [float(t) for t in arr['T_arr']],
                        'D_arr':      [float(d) for d in arr['D_arr']],
                        'D_err_arr':  [float(e) for e in arr['D_err_arr']],
                    }, _f, indent=2)
                mark_done(_phase3_done_marker)
                print(f'  Saved diffusivity_arrhenius.json → {_arr_out}')
        except Exception as _exc:
            print(f'\n  *** FAILED: {run_name}: {_exc} ***')
            print(f'  Skipping remaining phases for {run_name}; continuing with next (structure, n_H).')
            _FAILURES.append({'run_name': run_name, 'struct': struct_stem, 'n_h': n_h, 'error': str(_exc)})
            continue

_failures_path = os.path.join(WORK_DIR, 'diffusivity_failures.json')
with open(_failures_path, 'w') as _f:
    _json_lat.dump(_FAILURES, _f, indent=2)

if _FAILURES:
    print(f'\n=== Completed with {len(_FAILURES)} failure(s) — see {_failures_path} ===')
    for _fail in _FAILURES:
        print(f'  FAILED: {_fail["run_name"]}: {_fail["error"]}')
    sys.exit(1)
else:
    print('\n=== All structures and H concentrations complete ===')
"""

    os.makedirs(os.path.dirname(os.path.abspath(out_py)), exist_ok=True)
    with open(out_py, 'w') as fh:
        fh.write(_header + _body)
    return out_py


# ─────────────────────────────────────────────────────────────────────────────
# Cell addb050d — Generate diffusivity_run.sh
# ─────────────────────────────────────────────────────────────────────────────

def generate_orchestrator_sh(
    orch_job_name,
    orch_partition,
    orch_cpus_per_task,
    orch_mem,
    orch_time,
    orch_openmpi_ver,
    orch_cuda_version,
    orch_conda_env,
    orch_ld_paths,
    work_dir,
    out_py,
    out_sh: str,
) -> str:
    """Write diffusivity_run.sh and chmod +x it. Returns the output path."""

    orch_time_line = f'#SBATCH --time={orch_time}' if orch_time else ''
    _ld_lines = ('\n        ').join(
        f'export LD_LIBRARY_PATH={p}:$LD_LIBRARY_PATH'
        for p in orch_ld_paths
    )
    orch_output = f'{orch_job_name}_%j.out'

    content = textwrap.dedent(f"""\
        #!/bin/bash
        #SBATCH --job-name={orch_job_name}
        #SBATCH --partition={orch_partition}
        #SBATCH --ntasks=1
        #SBATCH --cpus-per-task={orch_cpus_per_task}
        #SBATCH --mem={orch_mem}
        #SBATCH --output={orch_output}
        {orch_time_line}

        module load OpenMPI/{orch_openmpi_ver}
        module load cuda/{orch_cuda_version}
        source ~/miniforge3/etc/profile.d/conda.sh
        conda activate {orch_conda_env}
        {_ld_lines}

        cd {work_dir}

        echo "Node: $(hostname)  Start: $(date)"
        python {out_py}
        echo "End: $(date)"
    """)

    os.makedirs(os.path.dirname(os.path.abspath(out_sh)), exist_ok=True)
    with open(out_sh, 'w') as fh:
        fh.write(content)
    os.chmod(out_sh, 0o755)
    return out_sh


# ─────────────────────────────────────────────────────────────────────────────
# Cell 1e1b6c9d — Load results
# ─────────────────────────────────────────────────────────────────────────────

_COL_NAMES = ['T_K', 'D', 'sigma_D', 'R2']


def load_diffusivity_results(
    input_structures,
    n_h_values,
    results_root,
) -> pd.DataFrame:
    """Scan results dirs and return a summary DataFrame (T_K, D, sigma_D, R2, struct, n_h)."""

    records = []
    for struct_path in input_structures:
        struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
        for n_h in n_h_values:
            run_name  = f'{struct_stem}_{n_h}H'
            table_txt = os.path.join(results_root, run_name, 'analysis', 'diffusivity_table.txt')
            if not os.path.exists(table_txt):
                print(f'  [MISSING] {table_txt}')
                continue
            df = pd.read_csv(
                table_txt,
                sep=r'\s+',
                comment='#',
                names=_COL_NAMES,
            )
            df['struct'] = struct_stem
            df['n_h']    = n_h
            records.append(df)

    if records:
        summary = pd.concat(records, ignore_index=True)
        print(f'Loaded {len(summary)} rows from {len(records)} completed runs.')
        _display(summary.head(12))
        return summary

    print('No completed results found. Run the cluster jobs first.')
    return pd.DataFrame()


# ─────────────────────────────────────────────────────────────────────────────
# Cell bf25ad41 — Minimisation QC
# ─────────────────────────────────────────────────────────────────────────────

def qc_minimizations(
    input_structures,
    n_h_values,
    results_root,
) -> pd.DataFrame:
    """Parse minimize_bare.out and minimize_h_{T}K.out; return QC DataFrame."""

    # Lazy import — parsers.py uses list[str] | None syntax (Python 3.10+)
    from models.parsers import parse_minimization_log

    min_records = []
    for struct_path in input_structures:
        struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
        for n_h in n_h_values:
            run_name = f'{struct_stem}_{n_h}H'
            for label, logname in [('bare', 'minimize_bare.out'), ('H', 'minimize_h.out')]:
                logfile = os.path.join(results_root, run_name, 'lammps_scripts', logname)
                if not os.path.exists(logfile):
                    logfile = os.path.join(results_root, run_name, logname)
                if not os.path.exists(logfile):
                    continue
                _, meta = parse_minimization_log(logfile)
                min_records.append({
                    'struct':    struct_stem,
                    'n_h':       n_h,
                    'step':      label,
                    'Ecoh_eV':   meta.get('Ecoh_eV_per_atom', float('nan')),
                    'a0_Ang':    meta.get('a0_Angstrom',      float('nan')),
                    'Fmax':      meta.get('Fmax_eV_per_Ang',  float('nan')),
                    'converged': meta.get('stop_criterion',   'unknown'),
                })

    if not min_records:
        print('No minimisation logs found (jobs may still be running).')
        return pd.DataFrame()

    min_df = pd.DataFrame(min_records)
    _display(min_df)
    bad = min_df[~min_df['converged'].str.contains('force', case=False, na=False)]
    if not bad.empty:
        print(f'\n{len(bad)} minimisation(s) may not have converged:')
        _display(bad[['struct', 'n_h', 'step', 'Fmax', 'converged']])
    else:
        print('All minimisations converged on force criterion.')
    return min_df


# ─────────────────────────────────────────────────────────────────────────────
# Cell db89af30 — NVT thermo + MSD QC
# ─────────────────────────────────────────────────────────────────────────────

def qc_nvt_thermo(
    input_structures,
    n_h_values,
    temperatures,
    results_root,
    timestep_ps: float = 0.0005,
) -> pd.DataFrame:
    """Parse NVT thermo logs; check temperature drift; save QC figures."""

    import matplotlib.pyplot as plt

    # Lazy import — parsers.py uses Python 3.10+ type union syntax
    from models.parsers import parse_equil_log, parse_thermo_series

    thermo_records = []
    for struct_path in input_structures:
        struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
        for n_h in n_h_values:
            run_name = f'{struct_stem}_{n_h}H'
            for T in temperatures:
                out_file = os.path.join(
                    results_root, run_name, 'results', f'{T}K', f'nvt_{T}K.out'
                )
                meta = parse_equil_log(out_file)
                if meta:
                    thermo_records.append({
                        'struct':      struct_stem,
                        'n_h':         n_h,
                        'T_set':       T,
                        'T_final_K':   meta.get('temp_final_K', float('nan')),
                        'PE_final_eV': meta.get('pe_final_eV',  float('nan')),
                    })

    if thermo_records:
        thermo_df = pd.DataFrame(thermo_records)
        _display(thermo_df)
        thermo_df['T_drift_%'] = (
            (thermo_df['T_final_K'] - thermo_df['T_set']).abs()
            / thermo_df['T_set'] * 100
        )
        drifty = thermo_df[thermo_df['T_drift_%'] > 5]
        if not drifty.empty:
            print(f'\n{len(drifty)} run(s) with >5% temperature drift:')
            _display(drifty[['struct', 'n_h', 'T_set', 'T_final_K', 'T_drift_%']])
        else:
            print('All NVT runs within 5% of target temperature.')
    else:
        print('No NVT thermo logs found (jobs may still be running).')
        return pd.DataFrame()

    for struct_path in input_structures:
        struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
        for n_h in n_h_values:
            run_name = f'{struct_stem}_{n_h}H'
            fig, axes = plt.subplots(
                2, len(temperatures),
                figsize=(3.5 * len(temperatures), 6),
                sharex='col',
            )
            has_data = False
            for col, T in enumerate(temperatures):
                out_file = os.path.join(
                    results_root, run_name, 'results', f'{T}K', f'nvt_{T}K.out'
                )
                msd_file = os.path.join(
                    results_root, run_name, 'results', f'{T}K', f'msd_{T}K.dat'
                )
                res = parse_thermo_series(out_file)
                if res is not None:
                    steps, temps_trace, _ = res
                    t_ps = steps * timestep_ps
                    axes[0][col].plot(t_ps, temps_trace, lw=0.6)
                    axes[0][col].axhline(T, color='red', lw=1, ls='--', label=f'{T} K')
                    axes[0][col].set_title(f'{T} K')
                    has_data = True
                if os.path.exists(msd_file):
                    try:
                        msd_data = np.loadtxt(msd_file, comments='#')
                        if msd_data.ndim == 2 and msd_data.shape[1] >= 2:
                            axes[1][col].plot(
                                msd_data[:, 0] * timestep_ps, msd_data[:, 1], lw=0.8
                            )
                            has_data = True
                    except Exception:
                        pass

            if has_data:
                axes[0][0].set_ylabel('Temperature (K)')
                axes[1][0].set_ylabel('MSD (Å²)')
                for col in range(len(temperatures)):
                    axes[1][col].set_xlabel('Time (ps)')
                fig.suptitle(f'{struct_stem} — {n_h} H atoms: Thermo QC', fontsize=12)
                fig.tight_layout()
                out_fig = os.path.join(
                    results_root, run_name, 'analysis', f'thermo_qc_{n_h}H.png'
                )
                os.makedirs(os.path.dirname(out_fig), exist_ok=True)
                plt.savefig(out_fig, dpi=120)
                plt.show()
                print(f'Saved: {out_fig}')
            else:
                plt.close()

    return thermo_df


# ─────────────────────────────────────────────────────────────────────────────
# Cell 607462a3 — D vs T plot
# ─────────────────────────────────────────────────────────────────────────────

def plot_D_vs_T(summary: pd.DataFrame, results_root: str) -> None:
    """D vs T plot (log scale, per structure, coloured by n_H)."""

    import matplotlib.pyplot as plt
    import matplotlib.cm as cm

    if summary.empty:
        print('No data to plot.')
        return

    structs  = summary['struct'].unique()
    n_h_list = sorted(summary['n_h'].unique())
    cmap      = cm.get_cmap('viridis', len(n_h_list))
    color_map = {nh: cmap(i) for i, nh in enumerate(n_h_list)}

    fig, axes = plt.subplots(
        1, len(structs),
        figsize=(5 * len(structs), 4),
        sharey=True,
        squeeze=False,
    )

    for col, struct in enumerate(structs):
        ax  = axes[0][col]
        sub = summary[summary['struct'] == struct]
        for n_h in n_h_list:
            d = sub[sub['n_h'] == n_h].sort_values('T_K')
            if d.empty:
                continue
            ax.errorbar(
                d['T_K'], d['D'],
                yerr=d['sigma_D'],
                fmt='o-', color=color_map[n_h],
                label=f'{n_h} H', capsize=3,
            )
        ax.set_xlabel('Temperature (K)')
        ax.set_title(struct)
        ax.set_yscale('log')
        ax.legend(title='n_H', fontsize=8)

    axes[0][0].set_ylabel('D (m²/s)')
    fig.suptitle('H Diffusivity vs Temperature', fontsize=13)
    fig.tight_layout()
    out_fig = os.path.join(results_root, 'D_vs_T.png')
    plt.savefig(out_fig, dpi=150)
    plt.show()
    print(f'Saved: {out_fig}')


# ─────────────────────────────────────────────────────────────────────────────
# Cell 413a7703 — Ea vs n_H plot
# ─────────────────────────────────────────────────────────────────────────────

def plot_Ea_vs_nH(
    input_structures,
    n_h_values,
    results_root,
) -> pd.DataFrame:
    """Arrhenius fits per (struct, n_h); plot Ea vs n_H; return arr_df."""

    import matplotlib.pyplot as plt
    from models.diffusivity_post_processing import run_arrhenius_pipeline

    arrhenius_records = []
    for struct_path in input_structures:
        struct_stem = os.path.splitext(os.path.basename(struct_path))[0]
        for n_h in n_h_values:
            run_name  = f'{struct_stem}_{n_h}H'
            table_txt = os.path.join(results_root, run_name, 'analysis', 'diffusivity_table.txt')
            if not os.path.exists(table_txt):
                continue
            arr = run_arrhenius_pipeline(
                diffusivity_file=table_txt,
                outdir=os.path.join(results_root, run_name, 'analysis'),
                plot_filename=f'arrhenius_{n_h}H.png',
            )
            arrhenius_records.append({
                'struct': struct_stem,
                'n_h':    n_h,
                'Ea':     arr['Ea'],
                'Ea_err': arr.get('Ea_err', 0.0),
                'D0':     arr['D0'],
                'D0_err': arr.get('D0_err', 0.0),
            })

    if not arrhenius_records:
        print('No Arrhenius fits computed.')
        return pd.DataFrame()

    arr_df = pd.DataFrame(arrhenius_records)
    _display(arr_df)

    fig, ax = plt.subplots(figsize=(6, 4))
    for struct, grp in arr_df.groupby('struct'):
        grp = grp.sort_values('n_h')
        ax.errorbar(
            grp['n_h'], grp['Ea'],
            yerr=grp['Ea_err'],
            fmt='o-', label=struct, capsize=4,
        )
    ax.set_xlabel('Number of H atoms')
    ax.set_ylabel('Activation energy Ea (eV)')
    ax.set_title('Arrhenius Ea vs H concentration')
    ax.legend()
    fig.tight_layout()
    out_fig = os.path.join(results_root, 'Ea_vs_nH.png')
    plt.savefig(out_fig, dpi=150)
    plt.show()
    print(f'Saved: {out_fig}')
    return arr_df


# ─────────────────────────────────────────────────────────────────────────────
# Cell 3caeefa9 — Arrhenius overlay
# ─────────────────────────────────────────────────────────────────────────────

def plot_arrhenius_overlay(
    summary: pd.DataFrame,
    arr_df: pd.DataFrame,
    temperatures,
    n_h_values,
    results_root: str,
) -> None:
    """log D vs 1000/T Arrhenius overlay for all n_H."""

    import matplotlib.pyplot as plt
    import matplotlib.cm as cm
    from models.diffusivity_post_processing import arrhenius_D

    if arr_df is None or arr_df.empty:
        print('Run plot_Ea_vs_nH first to compute arr_df.')
        return

    T_fit     = np.linspace(min(temperatures) - 20, max(temperatures) + 20, 200)
    inv_T_fit = 1000.0 / T_fit

    structs   = arr_df['struct'].unique()
    n_h_sorted = sorted(n_h_values)
    cmap      = cm.get_cmap('viridis', len(n_h_sorted))
    color_map = {nh: cmap(i) for i, nh in enumerate(n_h_sorted)}

    fig, axes = plt.subplots(
        1, len(structs),
        figsize=(5 * len(structs), 4),
        sharey=True, squeeze=False,
    )

    for col, struct in enumerate(structs):
        ax      = axes[0][col]
        sub_sum = summary[summary['struct'] == struct]
        sub_arr = arr_df[arr_df['struct'] == struct]

        for _, row in sub_arr.iterrows():
            n_h   = int(row['n_h'])
            color = color_map[n_h]
            D_line = arrhenius_D(T_fit, row['Ea'], row['D0'])
            ax.plot(inv_T_fit, np.log10(D_line), '-', color=color, lw=1.5)
            d = sub_sum[sub_sum['n_h'] == n_h].sort_values('T_K')
            ax.errorbar(
                1000.0 / d['T_K'],
                np.log10(d['D']),
                yerr=d['sigma_D'] / (np.log(10) * d['D']),
                fmt='o', color=color, capsize=3,
                label=f'{n_h} H  Ea={row["Ea"]:.2f} eV',
            )
        ax.set_xlabel('1000 / T  (K⁻¹)')
        ax.set_title(struct)
        ax.legend(fontsize=7, title='n_H', loc='lower right')

    axes[0][0].set_ylabel('log₁₀ D  (m²/s)')
    fig.suptitle('Arrhenius Plot — H Diffusivity', fontsize=13)
    fig.tight_layout()
    out_fig = os.path.join(results_root, 'arrhenius_overlay.png')
    plt.savefig(out_fig, dpi=150)
    plt.show()
    print(f'Saved: {out_fig}')
