"""
pipeline_workflow.py
====================
Script generator for the master pipeline orchestrator.

Generates pipeline_run.py which runs:
  - Part 1 (neb_run.py)          ─┐ in parallel
  - Part 3 (diffusivity_run.py)  ─┘
  then Part 2 (permeation_run.py) after both complete.
"""

from __future__ import annotations

import os
from pathlib import Path
from textwrap import dedent


def generate_pipeline_scripts(
    metals: list,
    diffusivity_run_py: str,
    work_dir: str,
    out_py: str,
) -> str:
    """Write pipeline_run.py for multiple metals. Returns path to written file.

    Parameters
    ----------
    metals : list of dict
        Each entry: {'stem': str, 'neb_run_py': str, 'permeation_run_py': str}
    diffusivity_run_py : str
        Path to diffusivity_run.py (handles all metals internally).
    work_dir : str
        Base calculation directory.
    out_py : str
        Output path for pipeline_run.py.
    """
    metals_repr = repr(metals)

    _header = f'''#!/usr/bin/env python3
"""
pipeline_run.py
===============
Master orchestrator — runs the full H permeation pipeline for each metal.

For each metal:
  Part 1 (neb_run_{{stem}}.py) runs in parallel with
  Part 3 (diffusivity_run.py) ─────────────────────► both must complete
  Part 2 (permeation_run_{{stem}}.py) ───────────────► runs after both complete

Generated by calculation/pipeline.ipynb — do not edit by hand.
"""

# -- config (injected by pipeline.ipynb) ----------------------------------------
METALS             = {metals_repr}
DIFFUSIVITY_RUN_PY = {diffusivity_run_py!r}
WORK_DIR           = {work_dir!r}

'''

    _body = r"""
import subprocess
import sys
import os

_python   = sys.executable
_base_dir = os.path.dirname(WORK_DIR)

print('=' * 70)
print(f'  Pipeline start: diffusivity + {len(METALS)} NEB job(s) in parallel')
print('=' * 70)

# -- Part 3 (diffusivity) + all Part 1 (NEB) in parallel ----------------------
_procs = {}

_log3 = os.path.join(WORK_DIR, 'diffusivity_run.log')
_procs['diffusivity'] = (
    subprocess.Popen([_python, DIFFUSIVITY_RUN_PY],
                     stdout=open(_log3, 'w'), stderr=subprocess.STDOUT,
                     cwd=_base_dir),
    _log3,
)
print(f'  diffusivity PID: {_procs["diffusivity"][0].pid}  log: {_log3}')

for _m in METALS:
    _stem = _m['stem']
    _log  = os.path.join(WORK_DIR, f'neb_run_{_stem}.log')
    _p    = subprocess.Popen([_python, _m['neb_run_py']],
                             stdout=open(_log, 'w'), stderr=subprocess.STDOUT,
                             cwd=_base_dir)
    _procs[f'neb_{_stem}'] = (_p, _log)
    print(f'  neb_{_stem} PID: {_p.pid}  log: {_log}')

# Wait for all parallel jobs
_failed = []
for _name, (_p, _log) in _procs.items():
    _rc = _p.wait()
    print(f'  {_name} returned: {_rc}')
    if _rc != 0:
        _failed.append((_name, _log))

if _failed:
    print('\nERROR: the following jobs failed — permeation will NOT run:')
    for _name, _log in _failed:
        print(f'  {_name}  log: {_log}')
    sys.exit(1)

# -- Part 2 (permeation) sequentially per metal --------------------------------
print('\n' + '=' * 70)
print('  All Part 1 + Part 3 complete.  Starting permeation (sequential)...')
print('=' * 70)

for _m in METALS:
    _stem = _m['stem']
    print(f'\n  [{_stem}] permeation start')
    _rc2 = subprocess.run([_python, _m['permeation_run_py']], cwd=_base_dir).returncode
    if _rc2 != 0:
        print(f'  ERROR: permeation failed for {_stem}')
        sys.exit(1)
    print(f'  [{_stem}] permeation complete')

print('\n' + '=' * 70)
print('  Pipeline complete.')
print('=' * 70)
"""

    Path(out_py).parent.mkdir(parents=True, exist_ok=True)
    with open(out_py, 'w') as fh:
        fh.write(_header + _body)
    print(f'Written: {out_py}')
    return out_py


def generate_pipeline_sh(
    orch_job_name: str,
    orch_partition: str,
    orch_cpus_per_task: int,
    orch_mem: str,
    orch_time: str | None,
    orch_openmpi_ver: str,
    orch_cuda_version: str,
    orch_conda_env: str,
    orch_ld_paths: list,
    out_py: str,
    out_sh: str,
) -> str:
    """Write the SLURM wrapper for pipeline_run.py. Returns path to written file."""

    _time_line = f'#SBATCH --time={orch_time}' if orch_time else ''

    _ld_export = ('\n        ').join(
        f'export LD_LIBRARY_PATH={p}:$LD_LIBRARY_PATH' for p in orch_ld_paths
    )

    _sh = dedent(f'''\
        #!/bin/bash
        #SBATCH --job-name={orch_job_name}
        #SBATCH --partition={orch_partition}
        #SBATCH --cpus-per-task={orch_cpus_per_task}
        #SBATCH --mem={orch_mem}
        {_time_line}
        #SBATCH --output={orch_job_name}_%j.out
        #SBATCH --error={orch_job_name}_%j.err

        # ── environment ──────────────────────────────────────────────────────────
        module load OpenMPI/{orch_openmpi_ver}
        module load cuda/{orch_cuda_version}
        source ~/miniforge3/etc/profile.d/conda.sh
        conda activate {orch_conda_env}
        {_ld_export}
        cd {os.path.dirname(out_py)}

        python {out_py}
    ''')

    Path(out_sh).parent.mkdir(parents=True, exist_ok=True)
    with open(out_sh, 'w') as fh:
        fh.write(_sh)
    print(f'Written: {out_sh}')
    return out_sh
