"""
pipeline_workflow.py
====================
Script generator for the master pipeline orchestrator.

Generates pipeline_run.py which runs:
  - Part 1 (neb_run.py)          ─┐ in parallel
  - Part 3 (diffusivity_run.py)  ─┘
  then Part 2 (permeation_run.py) after both complete.
"""

from __future__ import annotations

import os
from pathlib import Path
from textwrap import dedent


def generate_pipeline_scripts(
    neb_run_py: str,
    diffusivity_run_py: str,
    permeation_run_py: str,
    work_dir: str,
    out_py: str,
) -> str:
    """Write pipeline_run.py. Returns path to written file."""

    _header = f'''#!/usr/bin/env python3
"""
pipeline_run.py
===============
Master orchestrator — runs the three-part H permeation pipeline end-to-end.

  Part 1 (neb_run.py)         runs in parallel with
  Part 3 (diffusivity_run.py) ─────────────────────► both must complete
  Part 2 (permeation_run.py)  ─────────────────────► runs after both complete

Data flow (automatic — no manual handoff required):
  Part 1 → calculation/neb/ranked_barriers.json
         → calculation/neb/diss_vib_rates.json
         → calculation/adsorption/h_atom/
  Part 3 → calculation/results/diffusivity_arrhenius.json
         → calculation/results/lattice_params_vs_T.json
  Part 2 reads all of the above at runtime.

Generated by calculation/pipeline.ipynb — do not edit by hand.
"""

# -- config (injected by pipeline.ipynb) ----------------------------------------
NEB_RUN_PY         = {neb_run_py!r}
DIFFUSIVITY_RUN_PY = {diffusivity_run_py!r}
PERMEATION_RUN_PY  = {permeation_run_py!r}
WORK_DIR           = {work_dir!r}

'''

    _body = r"""
import subprocess
import sys
import os

print('=' * 70)
print('  Pipeline start: Part 1 (NEB) + Part 3 (diffusivity) in parallel')
print('=' * 70)

_python = sys.executable

_log1 = os.path.join(WORK_DIR, 'neb_run.log')
_log3 = os.path.join(WORK_DIR, 'diffusivity_run.log')
p1 = subprocess.Popen([_python, NEB_RUN_PY],
                      stdout=open(_log1, 'w'), stderr=subprocess.STDOUT)
p3 = subprocess.Popen([_python, DIFFUSIVITY_RUN_PY],
                      stdout=open(_log3, 'w'), stderr=subprocess.STDOUT)
print(f'  Part 1 PID: {p1.pid}  log: {_log1}')
print(f'  Part 3 PID: {p3.pid}  log: {_log3}')

rc1 = p1.wait()
rc3 = p3.wait()

print('\n' + '=' * 70)
print(f'  Part 1 returned: {rc1}')
print(f'  Part 3 returned: {rc3}')

if rc1 != 0 or rc3 != 0:
    print('ERROR: Part 1 and/or Part 3 failed — Part 2 will NOT be started.')
    print(f'  Part 1 log: {_log1}')
    print(f'  Part 3 log: {_log3}')
    sys.exit(1)

print('\n' + '=' * 70)
print('  Part 1 and Part 3 complete.  Starting Part 2 (permeation)...')
print('=' * 70)

rc2 = subprocess.run([_python, PERMEATION_RUN_PY]).returncode

print('\n' + '=' * 70)
print(f'  Part 2 returned: {rc2}')
if rc2 == 0:
    print('  Pipeline complete.')
else:
    print('  ERROR: Part 2 failed.')
    sys.exit(1)
"""

    Path(out_py).parent.mkdir(parents=True, exist_ok=True)
    with open(out_py, 'w') as fh:
        fh.write(_header + _body)
    print(f'Written: {out_py}')
    return out_py


def generate_pipeline_sh(
    orch_job_name: str,
    orch_partition: str,
    orch_cpus_per_task: int,
    orch_mem: str,
    orch_time: str | None,
    orch_openmpi_ver: str,
    orch_cuda_version: str,
    orch_conda_env: str,
    orch_ld_paths: list,
    out_py: str,
    out_sh: str,
) -> str:
    """Write the SLURM wrapper for pipeline_run.py. Returns path to written file."""

    _time_line = f'#SBATCH --time={orch_time}' if orch_time else ''

    _ld_export = ''
    for p in orch_ld_paths:
        _ld_export += f'export LD_LIBRARY_PATH={p}:$LD_LIBRARY_PATH\n'

    _sh = dedent(f'''\
        #!/bin/bash
        #SBATCH --job-name={orch_job_name}
        #SBATCH --partition={orch_partition}
        #SBATCH --cpus-per-task={orch_cpus_per_task}
        #SBATCH --mem={orch_mem}
        {_time_line}
        #SBATCH --output={orch_job_name}_%j.out
        #SBATCH --error={orch_job_name}_%j.err

        # ── environment ──────────────────────────────────────────────────────────
        source ~/miniforge3/etc/profile.d/conda.sh
        conda activate {orch_conda_env}
        {_ld_export}
        cd {os.path.dirname(out_py)}

        python {out_py}
    ''')

    Path(out_sh).parent.mkdir(parents=True, exist_ok=True)
    with open(out_sh, 'w') as fh:
        fh.write(_sh)
    print(f'Written: {out_sh}')
    return out_sh
