#!/usr/bin/env python3
"""
diffusivity_run.py
==================
Standalone H-diffusivity workflow orchestrator.
Submitted via diffusivity_run.sh (west partition, no GPU, no wall-time limit).

Loop: input_structures × n_h_values × temperatures
  Phase 1 : Minimise bulk  →  insert H  →  minimise bulk+H
  Phase 2 : NVT MD (chained SLURM GPU jobs, one per temperature)
  Phase 3 : MSD  →  D(T)  →  Arrhenius fit

Generated by calculation/diffusivity.ipynb — do not edit by hand.
"""

# ── config (injected by diffusivity.ipynb) ────────────────────────────────────
INPUT_STRUCTURES = ['/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation']
N_H_VALUES       = [1, 3, 5, 7, 10]
TEMPERATURES     = [300, 400, 500, 600, 700, 800]
WORK_DIR         = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation'
NVT_WALL_TIME    = '24:00:00'
CUTOFF           = '23:55:00'

import os
import sys
sys.path.insert(0, WORK_DIR)

from models.config import (
    LAMMPS_CMD, MACE_MODEL_LAMMPS, KOKKOS_FLAGS,
    PAIR_STYLE, PAIR_SUFFIX,
    E2T_7, MASSES_7, ELEM_STR_7,
    SLURM_DEFAULTS,
)
from models.structure import get_lattice_parameter, insert_hydrogen
from models.utils import make_run_dirs
from models.lammps_script import (
    write_minimization_script,
    write_nvt_bulk_script,
    write_nvt_bulk_restart_script,
)
from models.create_slurm import (
    write_slurm_job,
    write_chained_slurm_job,
    submit_slurm_job,
    wait_for_jobs,
)
from models.diffusivity_post_processing import (
    run_diffusivity_pipeline,
    save_diffusivity_table,
    run_arrhenius_pipeline,
)

GPU_SLURM_CFG = dict(SLURM_DEFAULTS, partition='multigpu', time=NVT_WALL_TIME)
KK = ' '.join(KOKKOS_FLAGS)

# ── main loop ─────────────────────────────────────────────────────────────────
for struct_path in INPUT_STRUCTURES:
    struct_stem = os.path.splitext(os.path.basename(struct_path))[0]

    for n_h in N_H_VALUES:
        run_name = f'{struct_stem}_{n_h}H'
        print(f'\n{"="*60}')
        print(f'  Structure : {struct_stem}   n_H : {n_h}')
        print(f'{"="*60}')

        # Directory layout created by make_run_dirs:
        #   results/{run_name}/structures/
        #   results/{run_name}/lammps_scripts/{T}K/
        #   results/{run_name}/slurm_scripts/{T}K/
        #   results/{run_name}/results/{T}K/
        dirs = make_run_dirs(
            name=run_name,
            temperatures=TEMPERATURES,
            base_dir=os.path.join(WORK_DIR, 'results'),
        )

        # Phase 1 scripts live one level up from the per-temperature dirs
        phase1_lmp_dir = os.path.join(dirs['root'], 'lammps_scripts')
        phase1_sh_dir  = os.path.join(dirs['root'], 'slurm_scripts')
        os.makedirs(phase1_lmp_dir, exist_ok=True)
        os.makedirs(phase1_sh_dir,  exist_ok=True)

        # ── Phase 1 ──────────────────────────────────────────────────────────
        print('\n--- Phase 1: Structure preparation ---')

        # 1a: minimise bare bulk
        min_bare_lmp = os.path.join(phase1_lmp_dir, 'minimize_bare.lammps')
        min_bare_out = os.path.join(dirs['structures'], 'bulk_min.lammps')
        min_bare_sh  = os.path.join(phase1_sh_dir,  'minimize_bare.sh')

        write_minimization_script(
            bulk_input=struct_path,
            min_output=min_bare_out,
            out_path=min_bare_lmp,
            pair_style=PAIR_STYLE,
            mace_model=MACE_MODEL_LAMMPS,
            pair_suffix=PAIR_SUFFIX,
            elem_str=ELEM_STR_7,
        )
        write_slurm_job(
            job_name=f'min_bare_{run_name}',
            slurm_config=GPU_SLURM_CFG,
            out_path=min_bare_sh,
            runner='lmp',
            lammps_cmd=LAMMPS_CMD,
            kokkos_flags=KOKKOS_FLAGS,
            script_path=min_bare_lmp,
        )
        jid = submit_slurm_job(min_bare_sh)
        wait_for_jobs({'min_bare': jid})
        print(f'  [1a] Bare bulk minimisation done.')

        # 1b: extract lattice parameter and insert H
        a0 = get_lattice_parameter(min_bare_out)
        print(f'  [1b] a0 = {a0:.4f} Å  →  inserting {n_h} H atom(s)')
        bulk_h_path, _, _ = insert_hydrogen(
            bulk_min_path=min_bare_out,
            n_h=n_h,
            masses=MASSES_7,
            e2t=E2T_7,
            out_dir=dirs['structures'],
            a0=a0,
        )

        # 1c: minimise bulk+H
        min_h_lmp = os.path.join(phase1_lmp_dir, 'minimize_h.lammps')
        min_h_out = os.path.join(dirs['structures'], 'bulk_min_h.lammps')
        min_h_sh  = os.path.join(phase1_sh_dir,  'minimize_h.sh')

        write_minimization_script(
            bulk_input=bulk_h_path,
            min_output=min_h_out,
            out_path=min_h_lmp,
            pair_style=PAIR_STYLE,
            mace_model=MACE_MODEL_LAMMPS,
            pair_suffix=PAIR_SUFFIX,
            elem_str=ELEM_STR_7,
        )
        write_slurm_job(
            job_name=f'min_h_{run_name}',
            slurm_config=GPU_SLURM_CFG,
            out_path=min_h_sh,
            runner='lmp',
            lammps_cmd=LAMMPS_CMD,
            kokkos_flags=KOKKOS_FLAGS,
            script_path=min_h_lmp,
        )
        jid = submit_slurm_job(min_h_sh)
        wait_for_jobs({'min_h': jid})
        print(f'  [1c] Bulk+H minimisation done.')

        # ── Phase 2 ──────────────────────────────────────────────────────────
        print('\n--- Phase 2: NVT MD ---')
        job_ids = {}

        for T in TEMPERATURES:
            lmp_dir = dirs[T]['lammps_scripts']
            sh_dir  = dirs[T]['slurm_scripts']
            res_dir = dirs[T]['results']
            rst_dir = os.path.join(res_dir, 'checkpoints')
            os.makedirs(rst_dir, exist_ok=True)

            nvt_lmp     = os.path.join(lmp_dir, f'nvt_{T}K.lammps')
            nvt_rst_lmp = os.path.join(lmp_dir, f'nvt_{T}K_restart.lammps')
            traj_file   = os.path.join(res_dir, f'nvt_{T}K.dump')
            out_file    = os.path.join(res_dir, f'nvt_{T}K.out')
            msd_file    = os.path.join(res_dir, f'msd_{T}K.dat')
            rst_glob    = os.path.join(rst_dir, f'nvt_{T}K.*.restart')
            chain_sh    = os.path.join(sh_dir,  f'nvt_{T}K_chain.sh')

            write_nvt_bulk_script(
                bulk_h_file=min_h_out,
                traj_file=traj_file,
                out_file=out_file,
                msd_file=msd_file,
                out_path=nvt_lmp,
                pair_style=PAIR_STYLE,
                mace_model=MACE_MODEL_LAMMPS,
                pair_suffix=PAIR_SUFFIX,
                elem_str=ELEM_STR_7,
                temperature=T,
                h_type=E2T_7['H'],
                restart_dir=rst_dir,
            )
            write_nvt_bulk_restart_script(
                restart_file=rst_glob,
                traj_file=traj_file,
                out_file=out_file,
                msd_file=msd_file,
                out_path=nvt_rst_lmp,
                pair_style=PAIR_STYLE,
                mace_model=MACE_MODEL_LAMMPS,
                pair_suffix=PAIR_SUFFIX,
                elem_str=ELEM_STR_7,
                temperature=T,
                h_type=E2T_7['H'],
                restart_dir=rst_dir,
            )
            write_chained_slurm_job(
                job_name=f'nvt_{T}K_{run_name}',
                slurm_config=GPU_SLURM_CFG,
                out_path=chain_sh,
                first_commands=[
                    f'{LAMMPS_CMD} {KK} -in {nvt_lmp} -log {out_file}',
                ],
                restart_commands=[
                    f'{LAMMPS_CMD} {KK} -in {nvt_rst_lmp} -log {out_file}',
                ],
                restart_glob=rst_glob,
                cutoff=CUTOFF,
                work_dir=WORK_DIR,
            )
            job_ids[f'{T}K'] = submit_slurm_job(chain_sh)
            print(f'  [2] Submitted NVT {T}K  →  job {job_ids[f"{T}K"]}')

        print(f'  Waiting for {len(job_ids)} NVT jobs ...')
        wait_for_jobs(job_ids)
        print('  All NVT jobs done.')

        # ── Phase 3 ──────────────────────────────────────────────────────────
        print('\n--- Phase 3: Post-processing ---')
        analysis_dir = os.path.join(dirs['root'], 'analysis')
        os.makedirs(analysis_dir, exist_ok=True)

        D_vals, D_errs, R2_vals = [], [], []
        for T in TEMPERATURES:
            dump   = os.path.join(dirs[T]['results'], f'nvt_{T}K.dump')
            result = run_diffusivity_pipeline(
                dump_file=dump,
                temperature=T,
                h_type=E2T_7['H'],
                outdir=analysis_dir,
            )
            D_vals.append(result['D'])
            D_errs.append(result['D_err'])
            R2_vals.append(result['R2'])
            print(f'  T={T}K   D={result["D"]:.4e} m2/s   R2={result["R2"]:.4f}')

        table_path = os.path.join(analysis_dir, 'diffusivity_table.txt')
        save_diffusivity_table(TEMPERATURES, D_vals, D_errs, R2_vals, table_path)

        arr = run_arrhenius_pipeline(
            diffusivity_file=table_path,
            outdir=analysis_dir,
        )
        print(f'  Ea = {arr["Ea"]:.4f} eV   D0 = {arr["D0"]:.4e} m2/s')

print('\n=== All structures and H concentrations complete ===')
