#!/usr/bin/env python3
"""
diffusivity_run.py
==================
Standalone H-diffusivity workflow orchestrator.
Submitted via diffusivity_run.sh (configured by notebook variables).

Loop: input_structures × n_h_values × temperatures
  Phase 1a: Minimise input bulk structure
  Phase 1b: NPT MD at each T → a0(T) → insert H → minimise bulk+H
  Phase 2 : NVT MD (chained SLURM GPU jobs, one per temperature)
  Phase 3 : MSD  →  D(T)  →  Arrhenius fit

Generated by calculation/diffusivity.ipynb — do not edit by hand.
"""

# ── config (injected by diffusivity.ipynb) ────────────────────────────────────
INPUT_STRUCTURES = ['/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Hastelloy_N_7_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Hastelloy_N_42_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Hastelloy_N_111_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Hastelloy_N_1234_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Hastelloy_N_12345_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Al_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Fe_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/Ni_supercell.lammps', '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/input_structure/bestsqs3.lmp']
N_H_VALUES       = [1, 3, 5, 10]
TEMPERATURES     = [400, 600, 800, 1000]
WORK_DIR         = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation'
NVT_WALL_TIME    = '24:00:00'
CUTOFF           = '23:55:00'
GPU_PARTITION        = 'multigpu'
GPU_TIME             = '24:00:00'
SHORT_GPU_PARTITION  = 'gpu'
SHORT_GPU_TIME       = '08:00:00'
SHORT_GPU_CUTOFF     = '07:55:00'
# MD defaults (ps units)
TIMESTEP_PS      = 0.0005
TAU_T_PS         = 0.1
N_EQUIL_STEPS    = 2000000
N_PROD_STEPS     = 5000000
THERMO_EVERY     = 1000
DUMP_EVERY       = 1000
VELOCITY_SEED    = 42
RESTART_EVERY    = 100000
# NPT Phase 1b
NPT_HEAT_STEPS   = 100000
NPT_PROD_STEPS   = 500000
NPT_BARO_DAMP    = 1.0
NPT_DUMP_EVERY   = 1000
# Minimisation (Phase 1a / Phase 1b bulk+H)
MIN_ETOL         = 0.0
MIN_FTOL         = 1e-08
MIN_MAXITER      = 50000
MIN_MAXEVAL      = 500000


import os
import sys
import json as _json_lat
sys.path.insert(0, os.path.dirname(WORK_DIR))

from models.config import (
    LAMMPS_CMD, MACE_MODEL_LAMMPS, KOKKOS_FLAGS,
    PAIR_STYLE, PAIR_SUFFIX,
    E2T_7, MASSES_7, ELEM_STR_7,
    SLURM_DEFAULTS,
)
from models.structure import get_lattice_parameter_from_dump, insert_hydrogen
from models.utils import make_run_dirs
from models.lammps_script import (
    write_minimization_script,
    write_npt_script,
    write_npt_restart_script,
    write_nvt_bulk_script,
    write_nvt_bulk_restart_script,
)
from models.create_slurm import (
    write_slurm_job,
    write_chained_slurm_job,
    submit_slurm_job,
    wait_for_jobs,
)
from models.diffusivity_post_processing import (
    run_diffusivity_pipeline,
    save_diffusivity_table,
    run_arrhenius_pipeline,
)

GPU_SLURM_CFG       = dict(SLURM_DEFAULTS, partition=GPU_PARTITION,      time=NVT_WALL_TIME)
SHORT_GPU_SLURM_CFG = dict(SLURM_DEFAULTS, partition=SHORT_GPU_PARTITION, time=SHORT_GPU_TIME)
KK = ' '.join(KOKKOS_FLAGS)

# ── main loop ─────────────────────────────────────────────────────────────────
for struct_path in INPUT_STRUCTURES:
    struct_stem = os.path.splitext(os.path.basename(struct_path))[0]

    for n_h in N_H_VALUES:
        run_name = f'{struct_stem}_{n_h}H'
        print(f'\n{"="*60}')
        print(f'  Structure : {struct_stem}   n_H : {n_h}')
        print(f'{"="*60}')

        dirs = make_run_dirs(
            name=run_name,
            temperatures=TEMPERATURES,
            base_dir=os.path.join(WORK_DIR, 'results'),
        )

        phase1_lmp_dir = os.path.join(dirs['root'], 'lammps_scripts')
        phase1_sh_dir  = os.path.join(dirs['root'], 'slurm_scripts')
        os.makedirs(phase1_lmp_dir, exist_ok=True)
        os.makedirs(phase1_sh_dir,  exist_ok=True)

        # ── Phase 1a ─────────────────────────────────────────────────────────
        print('\n--- Phase 1a: Minimise bare bulk ---')

        min_bare_lmp = os.path.join(phase1_lmp_dir, 'minimize_bare.lammps')
        min_bare_out = os.path.join(dirs['structures'], 'bulk_min.lammps')
        min_bare_sh  = os.path.join(phase1_sh_dir,  'minimize_bare.sh')

        if not os.path.exists(min_bare_out):
            write_minimization_script(
                bulk_input=struct_path,
                min_output=min_bare_out,
                out_path=min_bare_lmp,
                pair_style=PAIR_STYLE,
                mace_model=MACE_MODEL_LAMMPS,
                pair_suffix=PAIR_SUFFIX,
                elem_str=ELEM_STR_7,
                etol=MIN_ETOL,
                ftol=MIN_FTOL,
                maxiter=MIN_MAXITER,
                maxeval=MIN_MAXEVAL,
            )
            write_slurm_job(
                job_name=f'min_bare_{run_name}',
                slurm_config=SHORT_GPU_SLURM_CFG,
                out_path=min_bare_sh,
                runner='lmp',
                lammps_cmd=LAMMPS_CMD,
                kokkos_flags=KOKKOS_FLAGS,
                script_path=min_bare_lmp,
            )
            jid = submit_slurm_job(min_bare_sh)
            wait_for_jobs({'min_bare': jid})
            print(f'  [1a] Bare bulk minimisation done.  Output → {min_bare_out}')
        else:
            print(f'  [1a] Already exists: {min_bare_out} — skipping')

        # ── Phase 1b — Step A: NPT at every T in parallel ────────────────────
        print('\n--- Phase 1b: NPT equilibration at each temperature ---')

        npt_job_ids     = {}
        npt_final_paths = {}
        npt_stem = os.path.splitext(min_bare_out)[0]

        for T in TEMPERATURES:
            npt_lmp  = os.path.join(phase1_lmp_dir, f'npt_{T}K.lammps')
            npt_dump = os.path.join(dirs['structures'], f'npt_boxdims_{T}K.dat')
            npt_sh   = os.path.join(phase1_sh_dir,  f'npt_{T}K.sh')
            npt_final_paths[T] = f'{npt_stem}_npt_final_{T}K.lammps'

            npt_rst_lmp          = os.path.join(phase1_lmp_dir, f'npt_restart_{T}K.lammps')
            npt_after_heat_rst   = f'{os.path.splitext(npt_dump)[0]}_after_heat.restart'

            if not os.path.exists(npt_final_paths[T]):
                write_npt_script(
                    min_output=min_bare_out,
                    npt_dump=npt_dump,
                    out_path=npt_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=ELEM_STR_7,
                    target_t=T,
                    timestep=TIMESTEP_PS,
                    thermo_damp=TAU_T_PS,
                    baro_damp=NPT_BARO_DAMP,
                    heat_steps=NPT_HEAT_STEPS,
                    npt_steps=NPT_PROD_STEPS,
                    dump_every=NPT_DUMP_EVERY,
                )
                write_npt_restart_script(
                    restart_file=npt_after_heat_rst,
                    npt_dump=npt_dump,
                    min_output=min_bare_out,
                    out_path=npt_rst_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=ELEM_STR_7,
                    target_t=T,
                    timestep=TIMESTEP_PS,
                    thermo_damp=TAU_T_PS,
                    baro_damp=NPT_BARO_DAMP,
                    npt_steps=NPT_PROD_STEPS,
                    dump_every=NPT_DUMP_EVERY,
                )
                write_chained_slurm_job(
                    job_name=f'npt_{T}K_{run_name}',
                    slurm_config=SHORT_GPU_SLURM_CFG,
                    out_path=npt_sh,
                    first_commands=[f'{LAMMPS_CMD} {KK} -in {npt_lmp}'],
                    restart_commands=[f'{LAMMPS_CMD} {KK} -in {npt_rst_lmp}'],
                    restart_glob=npt_after_heat_rst,
                    cutoff=SHORT_GPU_CUTOFF,
                    work_dir=WORK_DIR,
                )
                npt_job_ids[f'npt_{T}K'] = submit_slurm_job(npt_sh)
                print(f'  Submitted NPT {T}K  →  job {npt_job_ids[f"npt_{T}K"]}')
            else:
                print(f'  [1b] NPT {T}K already done — skipping')

        print(f'  Waiting for {len(npt_job_ids)} NPT jobs ...')
        wait_for_jobs(npt_job_ids)
        print('  All NPT jobs done.')

        # ── Phase 1b — Step B: insert H at a0(T), minimise ───────────────────
        print('\n--- Phase 1b (cont.): Insert H and minimise at each temperature ---')

        min_h_job_ids = {}
        T_to_bulk_h   = {}
        _a0_by_T      = {}   # collect a0(T) in Å for each temperature

        for T in TEMPERATURES:
            _npt_dump_T = os.path.join(dirs['structures'], f'npt_boxdims_{T}K.dat')
            a0_T = get_lattice_parameter_from_dump(_npt_dump_T, n_last=50)
            _a0_by_T[T] = a0_T
            print(f'  [1b] T={T}K  a0 = {a0_T:.4f} Å')

            min_h_lmp_T = os.path.join(phase1_lmp_dir, f'minimize_h_{T}K.lammps')
            min_h_out_T = os.path.join(dirs['structures'], f'{T}K', 'bulk_min_h.lammps')
            min_h_sh_T  = os.path.join(phase1_sh_dir,  f'minimize_h_{T}K.sh')
            T_to_bulk_h[T] = min_h_out_T

            if not os.path.exists(min_h_out_T):
                bulk_h_path_T, _h_pos_T, _min_hm_T = insert_hydrogen(
                    bulk_min_path=npt_final_paths[T],
                    n_h=n_h,
                    masses=MASSES_7,
                    e2t=E2T_7,
                    out_dir=os.path.join(dirs['structures'], f'{T}K'),
                    a0=a0_T,
                )
                print(f'  [1b] T={T}K  inserted {n_h} H  min_H-metal={_min_hm_T:.3f} Å  → {bulk_h_path_T}')
                write_minimization_script(
                    bulk_input=bulk_h_path_T,
                    min_output=min_h_out_T,
                    out_path=min_h_lmp_T,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=ELEM_STR_7,
                    etol=MIN_ETOL,
                    ftol=MIN_FTOL,
                    maxiter=MIN_MAXITER,
                    maxeval=MIN_MAXEVAL,
                )
                write_slurm_job(
                    job_name=f'min_h_{T}K_{run_name}',
                    slurm_config=SHORT_GPU_SLURM_CFG,
                    out_path=min_h_sh_T,
                    runner='lmp',
                    lammps_cmd=LAMMPS_CMD,
                    kokkos_flags=KOKKOS_FLAGS,
                    script_path=min_h_lmp_T,
                )
                min_h_job_ids[f'min_h_{T}K'] = submit_slurm_job(min_h_sh_T)
            else:
                print(f'  [1b] bulk+H min {T}K already done — skipping')

        print(f'  Waiting for {len(min_h_job_ids)} bulk+H minimisation jobs ...')
        wait_for_jobs(min_h_job_ids)
        print('  All bulk+H minimisations done.')

        # Save temperature-dependent lattice parameters for Part 2 (permeation_run.py)
        _lat_out = os.path.join(WORK_DIR, 'results', 'lattice_params_vs_T.json')
        os.makedirs(os.path.dirname(_lat_out), exist_ok=True)
        with open(_lat_out, 'w') as _f:
            _json_lat.dump({'temperatures': list(_a0_by_T.keys()),
                            'a0_m': [v * 1e-10 for v in _a0_by_T.values()]}, _f, indent=2)
        print(f'  Saved lattice_params_vs_T.json → {_lat_out}')

        # ── Phase 2 ──────────────────────────────────────────────────────────
        print('\n--- Phase 2: NVT MD ---')
        job_ids = {}

        for T in TEMPERATURES:
            lmp_dir = dirs[T]['lammps_scripts']
            sh_dir  = dirs[T]['slurm_scripts']
            res_dir = dirs[T]['results']
            rst_dir = os.path.join(res_dir, 'checkpoints')
            os.makedirs(rst_dir, exist_ok=True)

            nvt_lmp     = os.path.join(lmp_dir, f'nvt_{T}K.lammps')
            nvt_rst_lmp = os.path.join(lmp_dir, f'nvt_{T}K_restart.lammps')
            traj_file   = os.path.join(res_dir, f'nvt_{T}K.dump')
            out_file    = os.path.join(res_dir, f'nvt_{T}K.out')
            msd_file    = os.path.join(res_dir, f'msd_{T}K.dat')
            rst_glob    = os.path.join(rst_dir, f'nvt_{T}K.*.restart')
            chain_sh    = os.path.join(sh_dir,  f'nvt_{T}K_chain.sh')

            if not os.path.exists(msd_file):
                write_nvt_bulk_script(
                    bulk_h_file=T_to_bulk_h[T],
                    traj_file=traj_file,
                    out_file=out_file,
                    msd_file=msd_file,
                    out_path=nvt_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=ELEM_STR_7,
                    temperature=T,
                    h_type=E2T_7['H'],
                    timestep=TIMESTEP_PS,
                    tau_t=TAU_T_PS,
                    n_equil=N_EQUIL_STEPS,
                    n_prod=N_PROD_STEPS,
                    thermo_every=THERMO_EVERY,
                    dump_every=DUMP_EVERY,
                    velocity_seed=VELOCITY_SEED,
                    restart_dir=rst_dir,
                    restart_every=RESTART_EVERY,
                )
                write_nvt_bulk_restart_script(
                    restart_file=rst_glob,
                    traj_file=traj_file,
                    out_file=out_file,
                    msd_file=msd_file,
                    out_path=nvt_rst_lmp,
                    pair_style=PAIR_STYLE,
                    mace_model=MACE_MODEL_LAMMPS,
                    pair_suffix=PAIR_SUFFIX,
                    elem_str=ELEM_STR_7,
                    temperature=T,
                    h_type=E2T_7['H'],
                    timestep=TIMESTEP_PS,
                    tau_t=TAU_T_PS,
                    n_equil=N_EQUIL_STEPS,
                    n_prod=N_PROD_STEPS,
                    thermo_every=THERMO_EVERY,
                    dump_every=DUMP_EVERY,
                    restart_dir=rst_dir,
                    restart_every=RESTART_EVERY,
                )
                write_chained_slurm_job(
                    job_name=f'nvt_{T}K_{run_name}',
                    slurm_config=GPU_SLURM_CFG,
                    out_path=chain_sh,
                    first_commands=[
                        f'{LAMMPS_CMD} {KK} -in {nvt_lmp} -log {out_file}',
                    ],
                    restart_commands=[
                        f'{LAMMPS_CMD} {KK} -in {nvt_rst_lmp} -log {out_file}',
                    ],
                    restart_glob=rst_glob,
                    cutoff=CUTOFF,
                    work_dir=WORK_DIR,
                )
                job_ids[f'{T}K'] = submit_slurm_job(chain_sh)
                print(f'  [2] Submitted NVT {T}K  →  job {job_ids[f"{T}K"]}')
            else:
                print(f'  [2] NVT {T}K already done — skipping')

        print(f'  Waiting for {len(job_ids)} NVT jobs ...')
        wait_for_jobs(job_ids)
        print('  All NVT jobs done.')

        # ── Phase 3 ──────────────────────────────────────────────────────────
        print('\n--- Phase 3: Post-processing ---')
        analysis_dir = os.path.join(dirs['root'], 'analysis')
        os.makedirs(analysis_dir, exist_ok=True)

        D_vals, D_errs, R2_vals = [], [], []
        for T in TEMPERATURES:
            dump   = os.path.join(dirs[T]['results'], f'nvt_{T}K.dump')
            result = run_diffusivity_pipeline(
                dump_file=dump,
                temperature=T,
                h_type=E2T_7['H'],
                outdir=analysis_dir,
            )
            D_vals.append(result['D'])
            D_errs.append(result['sigma_D'])
            R2_vals.append(result['R2'])
            print(f'  T={T}K   D={result["D"]:.4e} m2/s   R2={result["R2"]:.4f}')

        table_path = os.path.join(analysis_dir, 'diffusivity_table.txt')
        save_diffusivity_table(TEMPERATURES, D_vals, D_errs, R2_vals, table_path)

        print(f'  D(T) summary: {" | ".join(f"{T:.0f}K:{D:.2e}" for T, D in zip(TEMPERATURES, D_vals))}')
        arr = run_arrhenius_pipeline(
            diffusivity_file=table_path,
            outdir=analysis_dir,
        )
        print(f'  Arrhenius: Ea={arr["Ea"]:.4f} eV  D0={arr["D0"]:.4e} m²/s  R²={arr["R2"]:.4f}')

        # Save Arrhenius params so Part 2 (permeation_run.py) can load them
        _arr_out = os.path.join(WORK_DIR, 'results', 'diffusivity_arrhenius.json')
        with open(_arr_out, 'w') as _f:
            _json_lat.dump({
                'D0_m2s':     arr['D0'],
                'E_D_eV':     arr['Ea'],
                'D0_err':     arr['D0_err'],
                'E_D_err_eV': arr['Ea_err'],
                'R2_fit':     arr['R2'],
                'T_K_arr':    [float(t) for t in arr['T_arr']],
                'D_arr':      [float(d) for d in arr['D_arr']],
                'D_err_arr':  [float(e) for e in arr['D_err_arr']],
            }, _f, indent=2)
        print(f'  Saved diffusivity_arrhenius.json → {_arr_out}')

print('\n=== All structures and H concentrations complete ===')
