#!/usr/bin/env python3
"""
neb_run.py
==========
Standalone NEB workflow orchestrator for H2 dissociation barriers on Hastelloy N.
Submitted via neb_run.sh (configured by notebook variables).

Phase A : Build slab -> surface relax -> enumerate sites
Phase B : H2* adsorption (IS pool) -> H* adsorption (FS pool)
Phase C : FS pair enumeration -> deduplication -> cross-product -> proximity filter
          -> generate per-job NEB scripts + SLURM arrays
Phase D : Submit FS-min GPU array -> wait -> submit NEB CPU array -> wait
Phase E : Vibrational frequencies for dissociation IS + TS (ZPE corrections)

Generated by calculation/neb_calculation.ipynb -- do not edit by hand.
"""

# -- config (injected by neb_calculation.ipynb) --------------------------------
BULK_MIN_PATH  = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/structures/bulk_min.lammps'
WORK_DIR       = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation'
E_H2_GAS       = -6.790499
SLAB_DIR       = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/slabs'
ADS_DIR        = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/adsorption'
NEB_DIR        = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/neb'
MILLER         = (1, 1, 1)
LAYERS         = 12
VACUUM         = 15.0
LAT_REPEAT     = (5, 6)
# NEB pair-selection filters
SEP_MIN        = 2.5
SEP_MAX        = 6.0
GRAPH_DIST_MIN = 2
PROX_CUTOFF    = 5.0
# NEB calculation parameters
N_IMAGES       = 18
SPRING_CONST   = 1.0
NEB_FTOL       = 0.05
H_HEIGHT       = 1.5
# SLURM configurations
GPU_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 8, 'gpu': 'a100:1', 'conda_env': 'mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'multigpu', 'time': '04:00:00'}
NEB_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 16, 'gpu': None, 'conda_env': 'mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'short', 'time': '12:00:00'}
VIB_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 8, 'gpu': None, 'conda_env': 'mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'short', 'time': '06:00:00'}


import os
import sys
sys.path.insert(0, WORK_DIR)

from models.neb_workflow import orchestrate_full_neb_workflow
from models.create_slurm import submit_slurm_job, wait_for_jobs

result = orchestrate_full_neb_workflow(
    bulk_min_path=BULK_MIN_PATH,
    e_h2_gas=E_H2_GAS,
    slab_dir=SLAB_DIR,
    ads_dir=ADS_DIR,
    neb_dir=NEB_DIR,
    miller=MILLER,
    layers=LAYERS,
    vacuum=VACUUM,
    lateral_repeat=LAT_REPEAT,
    sep_min=SEP_MIN,
    sep_max=SEP_MAX,
    graph_dist_min=GRAPH_DIST_MIN,
    prox_cutoff=PROX_CUTOFF,
    n_images=N_IMAGES,
    spring_const=SPRING_CONST,
    neb_ftol=NEB_FTOL,
    h_height=H_HEIGHT,
    gpu_slurm_cfg=GPU_SLURM_CFG,
    neb_slurm_cfg=NEB_SLURM_CFG,
    dry_run=False,
)
print(f'  E_CLEAN  : {result["e_clean"]}')
print(f'  NEB jobs : {result["n_neb_jobs"]}')

# -- Phase D: Submit SLURM arrays ----------------------------------------------
print('\n' + '='*60)
print('  Phase D: Submit and wait')
print('='*60)

fsmin_jid = submit_slurm_job(result['fsmin_array_script'])
print(f'  FS-min array submitted  ->  job {fsmin_jid}')
wait_for_jobs({'fsmin_array': fsmin_jid})
print('  All FS minimisations done.')

neb_jid = submit_slurm_job(result['neb_array_script'])
print(f'  NEB array submitted  ->  job {neb_jid}')
wait_for_jobs({'neb_array': neb_jid})
print('  All NEB calculations done.')

# -- Phase E: Vibrational frequencies for dissociation IS + TS -----------------
print('\n' + '='*60)
print('  Phase E: Dissociation vibrational frequencies (ZPE corrections)')
print('='*60)

import json as _json_e
import glob as _glob_e

from models.config import MACE_MODEL_ASE as _MACE_ASE_E
from models.vibrations import orchestrate_vibrations as _orch_vib_e
from models.tst_rates import (
    split_vib_results as _split_vib_e,
    build_rate_dict as _brd_e,
)

_ranked_f_e = os.path.join(NEB_DIR, 'ranked_barriers.json')
if not os.path.exists(_ranked_f_e):
    print(f'WARNING: {_ranked_f_e} not found — Phase E skipped.')
else:
    with open(_ranked_f_e) as _f_e:
        _ranked_e = _json_e.load(_f_e)

    _vib_pairs_e  = []
    _neb_for_rd_e = {}
    _label_pair_e = {}

    for _job_e in _ranked_e:
        if not _job_e.get('converged', False):
            continue
        _lbl_e     = _job_e['label']
        _job_dir_e = os.path.join(NEB_DIR, _lbl_e)
        _is_e      = os.path.join(_job_dir_e, 'neb_initial.lammps')
        _img_dir_e = os.path.join(_job_dir_e, 'images')
        _path_f_e  = _job_e.get('path_file',
                                 os.path.join(_job_dir_e, 'neb_path.dat'))

        # TS = peak-energy intermediate image from neb_path.dat
        _ts_e = None
        if os.path.exists(_path_f_e):
            _rows_e = []
            with open(_path_f_e) as _pf_e:
                for _line_e in _pf_e:
                    if _line_e.startswith('#') or not _line_e.strip():
                        continue
                    _p_e = _line_e.split()
                    if len(_p_e) >= 3:
                        try:
                            _rows_e.append((float(_p_e[0]), float(_p_e[2])))
                        except ValueError:
                            pass
            if len(_rows_e) >= 3:
                _ts_idx_e = max(range(len(_rows_e)),
                                key=lambda _i: _rows_e[_i][1])
                _cands_e = _glob_e.glob(
                    os.path.join(_img_dir_e,
                                 f'image_{_ts_idx_e:02d}_*.lammps'))
                if _cands_e:
                    _ts_e = _cands_e[0]

        if not (os.path.exists(_is_e) and _ts_e and os.path.exists(_ts_e)):
            print(f'  [{_lbl_e}] IS or TS not found — skipping vib.')
            continue

        _vib_pairs_e.append((f'{_lbl_e}_IS', _is_e))
        _vib_pairs_e.append((f'{_lbl_e}_TS', _ts_e))
        _neb_for_rd_e[_lbl_e] = {
            'E_abs':     _job_e.get('Ea',      0.0),
            'E_des':     _job_e.get('E_des',   0.0),
            'delta_E':   _job_e.get('delta_E', 0.0),
            'converged': True,
        }
        try:
            _fs_e = _lbl_e.split('__')[-1]          # e.g. 'Ni_fcc+Mo_hcp'
            _e1_e = _fs_e.split('+')[0].split('_')[0]
            _e2_e = _fs_e.split('+')[1].split('_')[0]
            _label_pair_e[_lbl_e] = tuple(sorted([_e1_e, _e2_e]))
        except Exception:
            _label_pair_e[_lbl_e] = ('?', '?')

    print(f'  Diss vib pairs: {len(_vib_pairs_e)//2} IS/TS sets')

    if _vib_pairs_e:
        _vib_out_e = _orch_vib_e(
            structure_paths = _vib_pairs_e,
            outdir          = os.path.join(NEB_DIR, 'vibrations_diss'),
            mace_model_path = _MACE_ASE_E,
            slurm_opts      = VIB_SLURM_CFG,
            delta           = 0.01,
            device          = 'cpu',
            dry_run         = True,
        )
        from models.create_slurm import (
            submit_slurm_job as _sub_vib_e,
            wait_for_jobs    as _wait_vib_e,
        )
        _vib_jids_e = {_k: _sub_vib_e(_v['slurm'])
                       for _k, _v in _vib_out_e.items() if _v.get('slurm')}
        print(f'  Submitted {len(_vib_jids_e)} diss vib jobs.')
        _wait_vib_e(_vib_jids_e)
        print('  Diss vibrations complete.')

        _vib_is_e, _vib_ts_e = _split_vib_e(_vib_out_e)
        _rd_e = _brd_e(_neb_for_rd_e, _vib_is_e, _vib_ts_e,
                       T_K=700.0, apply_zpe=True)

        _diss_rates_e = {}
        for _lbl_rd, _r_e in _rd_e.items():
            _pair_e = _label_pair_e.get(_lbl_rd, ('?', '?'))
            _diss_rates_e[_lbl_rd] = {
                'pair':   list(_pair_e),
                'Ea_zpe': _r_e.get('Ea_zpe', _neb_for_rd_e[_lbl_rd]['E_abs']),
                'Ed_zpe': _r_e.get('Ed_zpe', _neb_for_rd_e[_lbl_rd]['E_des']),
                'Ea_raw': _r_e.get('Ea_raw', _neb_for_rd_e[_lbl_rd]['E_abs']),
                'Ed_raw': _r_e.get('Ed_raw', _neb_for_rd_e[_lbl_rd]['E_des']),
                'nu':     _r_e.get('nu',     1e13),
                'label':  _lbl_rd,
            }

        _diss_out_e = os.path.join(NEB_DIR, 'diss_vib_rates.json')
        with open(_diss_out_e, 'w') as _fw_e:
            _json_e.dump(_diss_rates_e, _fw_e, indent=2)
        print(f'  Saved diss_vib_rates.json '
              f'({len(_diss_rates_e)} labels) -> {_diss_out_e}')

print('\n' + '='*60)
print('  NEB workflow complete (incl. diss vibrations).')
print('='*60)
