#!/usr/bin/env python3
"""
permeation_run.py
==================
Standalone H permeation workflow orchestrator (Part 2).
Submitted via permeation_run.sh (SLURM wrapper generated by permeation.ipynb).

Phases:
  1 — Hop A NEB  (surface H* → subsurface-1 oct)
  2 — Hop B NEB  (subsurface-1 → subsurface-2 oct)
  3 — Vibrational frequencies (IS + TS, both hops)
  4 — TST rate constants at each temperature
  5 — KMC pressure sweeps at each temperature
  6 — Richardson-Sieverts permeability (all three S0 options)

Generated by calculation/permeation.ipynb — do not edit by hand.
"""

# ── Injected configuration ────────────────────────────────────────────────────
import os
import sys

_parent = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel'
if _parent not in sys.path:
    sys.path.insert(0, _parent)

WORK_DIR           = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation'
RELAXED_SLAB_PATH  = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/slabs/slab_relaxed.lammps'
SURFACE_SITES_JSON = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/slabs/surface_sites.json'
PHASE2_H_DIR       = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/adsorption/h_atom'
SUB_NEB_DIR        = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/neb_subsurface'
VIB_DIR            = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/vibrations'
RESULTS_DIR        = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/results'

TEMPERATURES   = [400, 600, 800, 1000]
P_VALS_PA      = [np.float64(1e-05), np.float64(1.9144819761699577e-05), np.float64(3.665241237079626e-05), np.float64(7.017038286703822e-05), np.float64(0.00013433993325989), np.float64(0.00025719138090593444), np.float64(0.0004923882631706741), np.float64(0.0009426684551178855), np.float64(0.0018047217668271701), np.float64(0.003455107294592218), np.float64(0.006614740641230145), np.float64(0.012663801734674034), np.float64(0.024244620170823284), np.float64(0.046415888336127774), np.float64(0.08886238162743407), np.float64(0.17012542798525893), np.float64(0.3257020655659783), np.float64(0.6235507341273913), np.float64(1.1937766417144358), np.float64(2.2854638641349885), np.float64(4.37547937507418), np.float64(8.376776400682925), np.float64(16.03718743751331), np.float64(30.702906297578497), np.float64(58.780160722749116), np.float64(112.53355826007646), np.float64(215.44346900318823), np.float64(412.4626382901348), np.float64(789.6522868499733), np.float64(1511.77507061566), np.float64(2894.2661247167516), np.float64(5541.020330009481), np.float64(10608.183551394482), np.float64(20309.17620904739), np.float64(38881.55180308085), np.float64(74438.03013251696), np.float64(142510.26703029964), np.float64(272833.33764867694), np.float64(522334.50742668327), np.float64(1000000.0)]
A0_M           = 3.52e-10
L_M            = 0.001

D0_M2S         = 1.5e-07    # m²/s — Arrhenius pre-exponential
E_D_EV         = 0.4    # eV   — diffusion activation energy
DH_DISS_EV     = None   # eV  — dissociation NEB delta_E (fill after NEB)
DH_ENTRY_EV    = None  # eV  — Hop A delta_E (fill after NEB)

NX             = 40
NY             = 40
SEED           = 42
KMC_MAX_STEPS  = 500000

N_IMAGES       = 18
SPRING_K       = 1.0
NEB_FTOL_VAL   = 0.05

GPU_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 8, 'gpu': 'a100:1', 'conda_env': '/home/akinyemi.az/miniforge3/envs/mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64', '/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'multigpu', 'time': '04:00:00'}
NEB_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 16, 'gpu': None, 'conda_env': '/home/akinyemi.az/miniforge3/envs/mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64', '/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'short', 'time': '12:00:00'}
VIB_SLURM_CFG  = {'ntasks': 1, 'cpus_per_task': 8, 'gpu': None, 'conda_env': '/home/akinyemi.az/miniforge3/envs/mace-lammps', 'cuda_version': '12.3.0', 'openmpi_ver': '4.1.6', 'ld_paths': ['/shared/EL9/explorer/cuda/12.3.0/lib64', '/shared/EL9/explorer/cuda/12.3.0/lib64/stubs', '/projects/westgroup/akinyemi.az/mace_lammps/lammps/build-mliap', '/home/akinyemi.az/miniforge3/envs/mace-lammps/lib'], 'partition': 'short', 'time': '06:00:00'}


# ── Runtime imports ────────────────────────────────────────────────────────────
import os
import sys
import json
import glob
import numpy as np
from ase.io import read as _ase_read

from models.config import MASSES_7, E2T_7, MACE_MODEL_ASE
from models.subsurface_graph import build_subsurface_graph, connect_to_surface
from models.neb_subsurface import orchestrate_hopa_neb, orchestrate_hopb_neb
from models.vibrations import collect_is_ts_paths, orchestrate_vibrations
from models.tst_rates import (
    collect_neb_results,
    split_vib_results,
    build_rate_dict,
    rates_to_json,
)
from models.permeation import (
    sweep_pressure,
    arrhenius_diffusivity,
    fit_solubility_from_kmc,
    lattice_site_S0,
    solubility_from_rates,
    sieverts_solubility,
    permeability,
    richardson_flux,
)
from models.parsers import parse_barrier_file
from models.create_slurm import submit_slurm_job, wait_for_jobs, auto_submit

os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(SUB_NEB_DIR, exist_ok=True)
os.makedirs(VIB_DIR, exist_ok=True)

_KB_EV = 8.617333262e-5   # eV/K

# ── Build subsurface graph ─────────────────────────────────────────────────────
print('Building subsurface graph …')
with open(SURFACE_SITES_JSON) as _f:
    _surf_data = json.load(_f)
G, subsurface_sites = build_subsurface_graph(RELAXED_SLAB_PATH, SURFACE_SITES_JSON, seed=42)
_slab_atoms = _ase_read(RELAXED_SLAB_PATH, format='lammps-data', atom_style='atomic')
_cell = _slab_atoms.get_cell()
surface_connections = connect_to_surface(subsurface_sites, _surf_data, _cell)
_sub1_n = sum(1 for s in subsurface_sites if s.get('layer_classification') == 'subsurface_1')
print(f'  subsurface-1 sites : {_sub1_n}')
print(f'  surface connections: {len(surface_connections)}')

# ── Collect dedup IS labels ────────────────────────────────────────────────────
dedup_is_labels = [
    (os.path.basename(p).replace('h_atom_', '').replace('_relaxed.lammps', ''), p, 0.0)
    for p in sorted(glob.glob(os.path.join(PHASE2_H_DIR, 'h_atom_*_relaxed.lammps')))
]
print(f'Dedup IS labels: {len(dedup_is_labels)}')
if not dedup_is_labels:
    raise FileNotFoundError(
        f'No h_atom_*_relaxed.lammps found in {PHASE2_H_DIR}. '
        'Run Part 1 (neb_calculation.ipynb) first.'
    )

# ══════════════════════════════════════════════════════════════════════════════
# Phase 1 — Hop A NEB: surface H* → subsurface-1 oct
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 1: Hop A NEB ──────────────────────────────────────────────────')
_hopa_jobs_json = os.path.join(SUB_NEB_DIR, 'hopa', 'hopa_jobs.json')
if not os.path.exists(_hopa_jobs_json):
    hopa_out = orchestrate_hopa_neb(
        dedup_is_labels    = dedup_is_labels,
        subsurface_graph   = (G, subsurface_sites),
        surface_connections= surface_connections,
        outdir             = SUB_NEB_DIR,
        masses             = MASSES_7,
        e2t                = E2T_7,
        slurm_opts         = GPU_SLURM_CFG,
        neb_slurm_opts     = NEB_SLURM_CFG,
        n_images           = N_IMAGES,
        spring_const       = SPRING_K,
        neb_ftol           = NEB_FTOL_VAL,
        dry_run            = True,
    )
    hopa_jobs = hopa_out['jobs']
    print(f'  Hop A: {hopa_out["n_jobs"]} jobs  fsmin_array={hopa_out["fsmin_array"]}')

    print('  Submitting Hop A FS-min …')
    auto_submit(
        array_script   = hopa_out['fsmin_array'],
        index_file     = os.path.join(SUB_NEB_DIR, 'hopa', 'job_index.txt'),
        result_dir     = os.path.join(SUB_NEB_DIR, 'hopa'),
        result_pattern = '*/sub1_fs_relaxed.lammps',
        n_total        = hopa_out['n_jobs'],
        job_name       = 'hopa_fsmin_array',
        queue_max      = 8,
        concurrent     = 4,
    )
    print('  Hop A FS-min done.')

    print('  Submitting Hop A NEB …')
    _jid_hopa_neb = submit_slurm_job(hopa_out['neb_array'])
    wait_for_jobs({'hopa_neb': _jid_hopa_neb})
    print('  Hop A NEB done.')
else:
    with open(_hopa_jobs_json) as _f:
        hopa_jobs = json.load(_f)
    print(f'  Hop A already done ({len(hopa_jobs)} jobs) — skipping')

# ══════════════════════════════════════════════════════════════════════════════
# Phase 2 — Hop B NEB: subsurface-1 → subsurface-2 oct
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 2: Hop B NEB ──────────────────────────────────────────────────')
_hopb_jobs_json = os.path.join(SUB_NEB_DIR, 'hopb', 'hopb_jobs.json')
if not os.path.exists(_hopb_jobs_json):
    hopb_out = orchestrate_hopb_neb(
        hopa_jobs          = hopa_jobs,
        hopa_outdir        = os.path.join(SUB_NEB_DIR, 'hopa'),
        subsurface_graph   = (G, subsurface_sites),
        outdir             = SUB_NEB_DIR,
        masses             = MASSES_7,
        e2t                = E2T_7,
        slurm_opts         = GPU_SLURM_CFG,
        neb_slurm_opts     = NEB_SLURM_CFG,
        n_images           = N_IMAGES,
        spring_const       = SPRING_K,
        neb_ftol           = NEB_FTOL_VAL,
        dry_run            = True,
    )
    hopb_jobs = hopb_out['jobs']
    print(f'  Hop B: {hopb_out["n_jobs"]} jobs  fsmin_array={hopb_out["fsmin_array"]}')

    print('  Submitting Hop B FS-min …')
    auto_submit(
        array_script   = hopb_out['fsmin_array'],
        index_file     = os.path.join(SUB_NEB_DIR, 'hopb', 'job_index.txt'),
        result_dir     = os.path.join(SUB_NEB_DIR, 'hopb'),
        result_pattern = '*/sub2_fs_relaxed.lammps',
        n_total        = hopb_out['n_jobs'],
        job_name       = 'hopb_fsmin_array',
        queue_max      = 8,
        concurrent     = 4,
    )
    print('  Hop B FS-min done.')

    print('  Submitting Hop B NEB …')
    _jid_hopb_neb = submit_slurm_job(hopb_out['neb_array'])
    wait_for_jobs({'hopb_neb': _jid_hopb_neb})
    print('  Hop B NEB done.')
else:
    with open(_hopb_jobs_json) as _f:
        hopb_jobs = json.load(_f)
    print(f'  Hop B already done ({len(hopb_jobs)} jobs) — skipping')

# ══════════════════════════════════════════════════════════════════════════════
# Phase 3 — Vibrational frequencies (IS + TS, both hops)
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 3: Vibrational frequencies ────────────────────────────────────')
_pairs_a = collect_is_ts_paths(hopa_jobs, hop='hopa', is_key='is_path')
_pairs_b = collect_is_ts_paths(hopb_jobs, hop='hopb', is_key='hopb_is')
_all_pairs = _pairs_a + _pairs_b
print(f'  Structures: {len(_all_pairs)} (IS + TS for both hops)')

vib_out = orchestrate_vibrations(
    structure_paths = _all_pairs,
    outdir          = VIB_DIR,
    mace_model_path = MACE_MODEL_ASE,
    slurm_opts      = VIB_SLURM_CFG,
    delta           = 0.01,
    device          = 'cpu',
    dry_run         = True,
)

_vib_jids = {}
for _lbl, _info in vib_out.items():
    if _info.get('slurm'):
        _vib_jids[_lbl] = submit_slurm_job(_info['slurm'])
print(f'  Submitted {len(_vib_jids)} vibration jobs.')
wait_for_jobs(_vib_jids)
print('  Vibrations done.')

# ══════════════════════════════════════════════════════════════════════════════
# Phase 4 — TST rate constants at each temperature
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 4: TST rate constants ──────────────────────────────────────────')
_neb_res_a = collect_neb_results(hopa_jobs, hop='hopa')
_neb_res_b = collect_neb_results(hopb_jobs, hop='hopb')
_neb_results = {**_neb_res_a, **_neb_res_b}
_vib_is, _vib_ts = split_vib_results(vib_out)
print(f'  NEB results: {len(_neb_results)} labels  IS: {len(_vib_is)}  TS: {len(_vib_ts)}')

for _T in TEMPERATURES:
    _rd = build_rate_dict(_neb_results, _vib_is, _vib_ts, T_K=_T, apply_zpe=True)
    _out_json = rates_to_json(_rd, os.path.join(RESULTS_DIR, f'rate_dict_T{int(_T)}K.json'))
    print(f'  T={_T:4.0f} K: {len(_rd)} rates → {_out_json}')

# ══════════════════════════════════════════════════════════════════════════════
# Phase 5 — KMC pressure sweeps
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 5: KMC pressure sweeps ──────────────────────────────────────────')
_DISS_JSON = os.path.join(WORK_DIR, 'neb', 'diss_jobs.json')
_NU_DISS   = 1e13   # s⁻¹ — fallback prefactor when ZPE rates unavailable

# T-dependent lattice parameter from Part 3 NPT MD
_LAT_JSON_5 = os.path.join(RESULTS_DIR, 'lattice_params_vs_T.json')
if os.path.exists(_LAT_JSON_5):
    with open(_LAT_JSON_5) as _f:
        _lat5 = json.load(_f)
    _a0_dict = dict(zip(_lat5['temperatures'], _lat5['a0_m']))
    print(f'  Loaded lattice_params_vs_T.json: {len(_a0_dict)} temperatures')
else:
    _a0_dict = {}
    print(f'  WARNING: lattice_params_vs_T.json not found — using fixed A0_M={A0_M} m')

# ZPE-corrected dissociation rates from Part 1 Phase E
_DISS_VIB_JSON = os.path.join(WORK_DIR, 'neb', 'diss_vib_rates.json')
_diss_vib = {}   # {tuple(pair): {Ea_zpe, Ed_zpe, nu}}
if os.path.exists(_DISS_VIB_JSON):
    with open(_DISS_VIB_JSON) as _f:
        _dv_raw = json.load(_f)
    for _dv_lbl, _dv in _dv_raw.items():
        _pkey = tuple(_dv['pair'])
        if _pkey not in _diss_vib or _dv.get('Ea_zpe', 9e9) < _diss_vib[_pkey]['Ea_zpe']:
            _diss_vib[_pkey] = {'Ea_zpe': _dv['Ea_zpe'],
                                 'Ed_zpe': _dv['Ed_zpe'],
                                 'nu':     _dv['nu']}
    print(f'  Loaded diss_vib_rates.json: {len(_diss_vib)} element pairs (ZPE-corrected)')
else:
    print(f'  WARNING: diss_vib_rates.json not found — using raw barriers for diss/des rates')

for _T in TEMPERATURES:
    _out = os.path.join(RESULTS_DIR, f'permeation_sweep_T{int(_T)}K.json')
    if os.path.exists(_out):
        print(f'  T={_T:4.0f} K  KMC sweep already done — skipping')
        continue

    with open(os.path.join(RESULTS_DIR, f'rate_dict_T{int(_T)}K.json')) as _f:
        _tst = json.load(_f)

    _kBT = _KB_EV * _T
    _a0_T = _a0_dict.get(_T, A0_M)
    _k_diss, _k_des, _k_entry, _k_exit = {}, {}, {}, {}

    for _lbl, _r in _tst.items():
        if _lbl.startswith('hopa_'):
            _sid = _lbl[len('hopa_'):]
            for _el in ('Ni', 'Mo', 'Cr', 'Fe'):
                if _el in _sid:
                    _k_entry[_el] = _r['k_forward']
                    _k_exit[_el]  = _r['k_reverse']
                    break

    if _diss_vib:
        for _pkey5, _dv5 in _diss_vib.items():
            _k_diss[_pkey5] = np.exp(-_dv5['Ea_zpe'] / _kBT)
            _k_des[_pkey5]  = _dv5['nu'] * np.exp(-_dv5['Ed_zpe'] / _kBT)
    elif os.path.exists(_DISS_JSON):
        with open(_DISS_JSON) as _f:
            _diss = json.load(_f)
        for _job in _diss:
            _bf = _job.get('barrier_file', '')
            if not os.path.exists(_bf):
                continue
            _bd   = parse_barrier_file(_bf)
            _pair = tuple(sorted(_job['sid'].replace('-', '').split('_')[:2]))
            _k_diss[_pair] = np.exp(-_bd['E_abs'] / _kBT)
            _k_des[_pair]  = _NU_DISS * np.exp(-_bd['E_des'] / _kBT)
    else:
        print(f'  WARNING: no diss rate source found — using placeholders at T={_T} K')
        for _pair in [('Ni', 'Ni'), ('Mo', 'Ni'), ('Cr', 'Ni'), ('Fe', 'Ni'),
                      ('Mo', 'Mo'), ('Cr', 'Mo'), ('Fe', 'Mo'),
                      ('Cr', 'Cr'), ('Fe', 'Cr'), ('Fe', 'Fe')]:
            _k_diss[_pair] = np.exp(-0.5  / _kBT)
            _k_des[_pair]  = _NU_DISS * np.exp(-1.2 / _kBT)

    for _el, _ke in _k_entry.items():
        print(f'  [{_T:.0f}K] k_entry({_el})={_ke:.3e} s⁻¹  k_exit({_el})={_k_exit.get(_el, float("nan")):.3e} s⁻¹')
    _rate_dict = {'k_diss': _k_diss, 'k_des': _k_des,
                  'k_entry': _k_entry, 'k_exit': _k_exit}
    _D_T = arrhenius_diffusivity(D0_M2S, E_D_EV, _T)
    np.random.seed(SEED)
    _sweep = sweep_pressure(
        P_vals_Pa  = P_VALS_PA,
        rate_dict  = _rate_dict,
        D_m2s      = _D_T,
        L_m        = L_M,
        T_K        = _T,
        a0_m       = _a0_T,
        nx         = NX,
        ny         = NY,
        seed       = SEED,
        kmc_kwargs = {'window': 2000, 'rtol': 0.02, 'max_steps': KMC_MAX_STEPS},
    )
    _sweep['T_K']   = _T
    _sweep['D_m2s'] = _D_T
    _sweep['a0_m']  = _a0_T
    with open(_out, 'w') as _f:
        json.dump(_sweep, _f, indent=2)
    _conv = sum(1 for c in _sweep.get('converged', []) if c)
    print(f'  T={_T:4.0f} K  a0={_a0_T:.4e} m  D={_D_T:.2e} m²/s  '
          f'{_conv}/{len(P_VALS_PA)} converged → {_out}')

# ══════════════════════════════════════════════════════════════════════════════
# Phase 6 — Richardson-Sieverts permeability (all three S₀ options)
# ══════════════════════════════════════════════════════════════════════════════
print('\n── Phase 6: Richardson-Sieverts permeability ────────────────────────────')

# Auto-extract DH values from NEB results if not set manually
_DH_DISS_USED  = DH_DISS_EV
_DH_ENTRY_USED = DH_ENTRY_EV

if _DH_ENTRY_USED is None:
    _fst_rd_f = os.path.join(RESULTS_DIR, f'rate_dict_T{int(TEMPERATURES[0])}K.json')
    if os.path.exists(_fst_rd_f):
        with open(_fst_rd_f) as _f: _fst_rd = json.load(_f)
        _hopa_de = [_r.get('delta_e', 0.0) for _lbl, _r in _fst_rd.items()
                    if _lbl.startswith('hopa_')]
        if _hopa_de:
            _DH_ENTRY_USED = float(np.mean(_hopa_de))
            print(f'  Auto-extracted DH_ENTRY_EV = {_DH_ENTRY_USED:.4f} eV '
                  f'(mean of {len(_hopa_de)} Hop A barriers)')

if _DH_DISS_USED is None:
    _ranked6_f = os.path.join(WORK_DIR, 'neb', 'ranked_barriers.json')
    if os.path.exists(_ranked6_f):
        with open(_ranked6_f) as _f: _ranked6 = json.load(_f)
        _diss_de6 = [_r.get('delta_E', 0.0) for _r in _ranked6
                     if _r.get('converged', False)]
        if _diss_de6:
            _DH_DISS_USED = float(np.mean(_diss_de6))
            print(f'  Auto-extracted DH_DISS_EV  = {_DH_DISS_USED:.4f} eV '
                  f'(mean of {len(_diss_de6)} converged diss barriers)')

if _DH_DISS_USED is None or _DH_ENTRY_USED is None:
    print('WARNING: DH_DISS_EV or DH_ENTRY_EV could not be determined — skipping Phase 6.')
    print('  Fill DH_DISS_EV and DH_ENTRY_EV in permeation.ipynb Cell 2 and regenerate.')
else:
    _DH_SOL = _DH_DISS_USED / 2.0 + _DH_ENTRY_USED
    _P_HIGH = max(P_VALS_PA)

    for _T in TEMPERATURES:
        with open(os.path.join(RESULTS_DIR, f'permeation_sweep_T{int(_T)}K.json')) as _f:
            _sw = json.load(_f)
        _D_T  = arrhenius_diffusivity(D0_M2S, E_D_EV, _T)
        _a0_T6 = _a0_dict.get(_T, A0_M)
        _kBT6  = _KB_EV * _T

        # Option 1 — lattice site density (per-T a₀)
        _S0_lat6 = lattice_site_S0(_a0_T6)
        _S1      = sieverts_solubility(_DH_SOL, _S0_lat6, _T)
        _Phi1    = permeability(_D_T, _S1)
        _J1      = richardson_flux(_Phi1, _P_HIGH, 0.0, L_M)

        # Option 2 — TST detailed balance (first Hop A rate as representative)
        with open(os.path.join(RESULTS_DIR, f'rate_dict_T{int(_T)}K.json')) as _f:
            _rd2 = json.load(_f)
        _repr_entry, _repr_exit = 1e9, 1e8
        for _lbl, _r in _rd2.items():
            if _lbl.startswith('hopa_'):
                _repr_entry, _repr_exit = _r['k_forward'], _r['k_reverse']
                break
        if _diss_vib:
            _dv0_t = next(iter(_diss_vib.values()))
            _repr_diss = np.exp(-_dv0_t['Ea_zpe'] / _kBT6)
            _repr_des  = _dv0_t['nu'] * np.exp(-_dv0_t['Ed_zpe'] / _kBT6)
        else:
            _repr_diss = np.exp(-0.5  / _kBT6)
            _repr_des  = _NU_DISS * np.exp(-1.2 / _kBT6)
        _S2   = solubility_from_rates(_repr_diss, _repr_des, _repr_entry, _repr_exit,
                                      _a0_T6, _T)
        _Phi2 = permeability(_D_T, _S2)
        _J2   = richardson_flux(_Phi2, _P_HIGH, 0.0, L_M)

        # Option 3 — KMC empirical Sieverts fit
        _kmc_sol = fit_solubility_from_kmc(_sw)
        _S3   = _kmc_sol['S_mean']
        _Phi3 = permeability(_D_T, _S3)
        _J3   = richardson_flux(_Phi3, _P_HIGH, 0.0, L_M)

        _perm_f = os.path.join(RESULTS_DIR, f'permeability_T{int(_T)}K.json')
        with open(_perm_f, 'w') as _f:
            json.dump({
                'T_K': _T, 'D0_m2s': D0_M2S, 'E_D_eV': E_D_EV,
                'dH_sol_eV': _DH_SOL, 'a0_m': _a0_T6,
                'dH_diss_eV': _DH_DISS_USED, 'dH_entry_eV': _DH_ENTRY_USED,
                'option1': {'S': _S1, 'Phi': _Phi1, 'J': _J1},
                'option2': {'S': _S2, 'Phi': _Phi2, 'J': _J2},
                'option3': {'S': _S3, 'Phi': _Phi3, 'J': _J3,
                            'S_std':       _kmc_sol['S_std'],
                            'n_converged': _kmc_sol['n_converged']},
                'P_high_Pa': _P_HIGH, 'L_m': L_M,
            }, _f, indent=2)
        print(f'  T={_T:4.0f} K  Opt1(lattice):  S={_S1:.3e}  Phi={_Phi1:.3e}  J={_J1:.3e} atoms/m²/s')
        print(f'  T={_T:4.0f} K  Opt2(TST):      S={_S2:.3e}  Phi={_Phi2:.3e}  J={_J2:.3e} atoms/m²/s')
        print(f'  T={_T:4.0f} K  Opt3(KMC):      S={_S3:.3e}  Phi={_Phi3:.3e}  J={_J3:.3e} atoms/m²/s')

    # Multi-T Arrhenius S₀ fit from KMC
    _S_arr, _T_arr = [], []
    for _T in TEMPERATURES:
        _sw_f = os.path.join(RESULTS_DIR, f'permeation_sweep_T{int(_T)}K.json')
        if not os.path.exists(_sw_f):
            continue
        with open(_sw_f) as _f:
            _sw = json.load(_f)
        _sol = fit_solubility_from_kmc(_sw)
        if _sol['n_converged'] > 0:
            _S_arr.append(_sol['S_mean'])
            _T_arr.append(float(_T))

    if len(_S_arr) >= 2:
        _S_np    = np.array(_S_arr)
        _T_np    = np.array(_T_arr)
        _slope, _inter = np.polyfit(1.0 / _T_np, np.log(_S_np), 1)
        _dH_kmc  = -_slope * _KB_EV
        _S0_kmc  = np.exp(_inter)
        _log_pred = _slope / _T_np + _inter
        _ss_res  = np.sum((np.log(_S_np) - _log_pred) ** 2)
        _ss_tot  = np.sum((np.log(_S_np) - np.mean(np.log(_S_np))) ** 2)
        _r2      = 1.0 - _ss_res / _ss_tot if _ss_tot > 0.0 else 1.0
        _sol_out = os.path.join(RESULTS_DIR, 'solubility_arrhenius_kmc.json')
        with open(_sol_out, 'w') as _f:
            json.dump({'T_K_arr':       _T_arr,
                       'S_mean_arr':    _S_arr,
                       'S0_kmc':        _S0_kmc,
                       'dH_sol_kmc_eV': _dH_kmc,
                       'r2_fit':        _r2,
                       'D0_m2s':        D0_M2S,
                       'E_D_eV':        E_D_EV}, _f, indent=2)
        print(f'\nArrhenius  S0={_S0_kmc:.3e}  dH_sol={_dH_kmc:.3f} eV  R²={_r2:.4f} → {_sol_out}')
    else:
        print('WARNING: fewer than 2 valid temperatures — Arrhenius S₀ fit skipped.')

# Save Arrhenius diffusivity params so kmc_calculation.ipynb Cell 1 can load them
_diff_out = os.path.join(RESULTS_DIR, 'diffusivity_arrhenius.json')
with open(_diff_out, 'w') as _f:
    json.dump({'D0_m2s': D0_M2S, 'E_D_eV': E_D_EV}, _f, indent=2)
print(f'\nSaved diffusivity Arrhenius params → {_diff_out}')
print('=== permeation_run.py complete ===')
