#!/usr/bin/env python3
"""
pipeline_run.py
===============
Master orchestrator — runs the three-part H permeation pipeline end-to-end.

  Part 1 (neb_run.py)         runs in parallel with
  Part 3 (diffusivity_run.py) ─────────────────────► both must complete
  Part 2 (permeation_run.py)  ─────────────────────► runs after both complete

Data flow (automatic — no manual handoff required):
  Part 1 → calculation/neb/ranked_barriers.json
         → calculation/neb/diss_vib_rates.json
         → calculation/adsorption/h_atom/
  Part 3 → calculation/results/diffusivity_arrhenius.json
         → calculation/results/lattice_params_vs_T.json
  Part 2 reads all of the above at runtime.

Generated by calculation/pipeline.ipynb — do not edit by hand.
"""

# -- config (injected by pipeline.ipynb) ----------------------------------------
NEB_RUN_PY         = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/neb_run.py'
DIFFUSIVITY_RUN_PY = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/diffusivity_run.py'
PERMEATION_RUN_PY  = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation/permeation_run.py'
WORK_DIR           = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/calculation'


import subprocess
import sys
import os

print('=' * 70)
print('  Pipeline start: Part 1 (NEB) + Part 3 (diffusivity) in parallel')
print('=' * 70)

_python = sys.executable
_base_dir = os.path.dirname(WORK_DIR)

_log1 = os.path.join(WORK_DIR, 'neb_run.log')
_log3 = os.path.join(WORK_DIR, 'diffusivity_run.log')
p1 = subprocess.Popen([_python, NEB_RUN_PY],
                      stdout=open(_log1, 'w'), stderr=subprocess.STDOUT,
                      cwd=_base_dir)
p3 = subprocess.Popen([_python, DIFFUSIVITY_RUN_PY],
                      stdout=open(_log3, 'w'), stderr=subprocess.STDOUT,
                      cwd=_base_dir)
print(f'  Part 1 PID: {p1.pid}  log: {_log1}')
print(f'  Part 3 PID: {p3.pid}  log: {_log3}')

rc1 = p1.wait()
rc3 = p3.wait()

print('\n' + '=' * 70)
print(f'  Part 1 returned: {rc1}')
print(f'  Part 3 returned: {rc3}')

if rc1 != 0 or rc3 != 0:
    print('ERROR: Part 1 and/or Part 3 failed — Part 2 will NOT be started.')
    print(f'  Part 1 log: {_log1}')
    print(f'  Part 3 log: {_log3}')
    sys.exit(1)

print('\n' + '=' * 70)
print('  Part 1 and Part 3 complete.  Starting Part 2 (permeation)...')
print('=' * 70)

rc2 = subprocess.run([_python, PERMEATION_RUN_PY], cwd=_base_dir).returncode

print('\n' + '=' * 70)
print(f'  Part 2 returned: {rc2}')
if rc2 == 0:
    print('  Pipeline complete.')
else:
    print('  ERROR: Part 2 failed.')
    sys.exit(1)
