#!/usr/bin/env python3
# ASE CINEB — generated by models.ase_neb.write_ase_neb_script
# IS: sub1:ss_3
# FS: sub2:ss_22
# Interpolation: IDPP
# Two-phase: regular NEB (phase 1) → CINEB (phase 2)

import os, sys
import numpy as np

# Strip cpu stubs from LD_LIBRARY_PATH — causes segfault on some nodes
_ld = os.environ.get("LD_LIBRARY_PATH", "")
os.environ["LD_LIBRARY_PATH"] = ":".join(
    p for p in _ld.split(":") if "stubs" not in p)

from pathlib import Path as _Path
from ase.io import read, Trajectory as _Trajectory
from ase.mep import NEB
from ase.optimize import MDMin
from ase.calculators.singlepoint import SinglePointCalculator
from mace.calculators import MACECalculator

# ── Parameters injected from notebook ─────────────────────────────
MACE_MODEL      = "/projects/westgroup/akinyemi.az/mace_lammps/models/mace-mh-1.model"
NEB_IS_FILE     = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopa/s_0/sub1_fs_relaxed.lammps"
FS_RELAXED_DATA = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/sub2_fs_relaxed.lammps"
Z_FREEZE_CUTOFF = 12.93353452688152    # Å — frozen layer threshold
E_IS            = -124.8649468604               # eV — from LAMMPS IS minimisation
def _parse_pe_final(log_path):
    _val = None
    with open(log_path) as _f:
        for _line in _f:
            if 'pe_final_eV' in _line and ':' in _line:
                try:
                    _val = float(_line.split(':')[1].strip())
                except ValueError:
                    pass
    if _val is None:
        raise ValueError(f"pe_final_eV not found in {log_path}")
    return _val

E_FS = _parse_pe_final("/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/fs_min.log")  # eV — from fs_min.log at runtime
N_IMAGES        = 6           # intermediate images
SPRING_CONST    = 1.0       # eV/Å²
NEB_FMAX        = 0.1           # eV/Å — CINEB convergence
N1_FMAX         = NEB_FMAX * 3         # eV/Å — phase 1 (looser)
N1_STEPS        = 5000
NEB_STEPS       = 10000
DEVICE          = "cpu"
BARRIER_FILE    = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/neb_barrier.txt"
PATH_FILE       = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/neb_path.dat"
LOG_PHASE1      = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/hopb_phase1.log"
LOG_PHASE2      = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/hopb_phase2.log"
LABEL_IS        = "sub1:ss_3"
LABEL_FS        = "sub2:ss_22"
IMAGES_DIR      = "/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/images"
TRAJ_PHASE1     = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/hopb_phase1.traj'
TRAJ_PHASE2     = '/projects/westgroup/akinyemi.az/mace_lammps/MHI_Nickel/tests/pipeline/work/diffusivity/neb_subsurface/ni_bulk_test/hopb/s_0/hopb_phase2.traj'

# ── Calculator with frozen layers ─────────────────────────────────
class MACEFrozenCalc(MACECalculator):
    def get_forces(self, atoms=None):
        forces = super().get_forces(atoms).copy()
        a = self.atoms if atoms is None else atoms
        forces[a.get_positions()[:, 2] < Z_FREEZE_CUTOFF] = 0.0
        return forces

def make_calc():
    return MACEFrozenCalc(
        model_paths=MACE_MODEL, device=DEVICE, default_dtype="float64", head="omat_pbe")

# ── Load structures and pin endpoint energies ─────────────────────
is_raw = read(NEB_IS_FILE, format="lammps-data", atom_style="atomic")
is_raw.wrap()
fs_raw = read(FS_RELAXED_DATA, format="lammps-data", atom_style="atomic")
fs_raw.wrap()

def pin(atoms, energy):
    atoms = atoms.copy()
    atoms.calc = SinglePointCalculator(atoms)
    atoms.calc.results = {"energy": energy,
                           "forces": np.zeros((len(atoms), 3))}
    return atoms

is_end = pin(is_raw, E_IS)
fs_end = pin(fs_raw, E_FS)

# ── Restart detection / IDPP interpolation ───────────────────────
def _load_last_band(traj_path):
    _t = _Trajectory(traj_path)
    _n = len(_t)
    _last = max(0, _n - (N_IMAGES + 2))
    return [_t[_last + _i] for _i in range(min(N_IMAGES + 2, _n - _last))]

if TRAJ_PHASE2 and _Path(TRAJ_PHASE2).exists():
    print("Restart: Phase 2 checkpoint found — resuming CINEB")
    sys.stdout.flush()
    images = _load_last_band(TRAJ_PHASE2)
    for img in images[1:-1]:
        img.calc = make_calc()
    neb = NEB(images, climb=True, k=SPRING_CONST, method="aseneb")
    _restart_phase = 2
elif TRAJ_PHASE1 and _Path(TRAJ_PHASE1).exists():
    print("Restart: Phase 1 checkpoint found — starting Phase 2")
    sys.stdout.flush()
    images = _load_last_band(TRAJ_PHASE1)
    for img in images[1:-1]:
        img.calc = make_calc()
    neb = NEB(images, climb=True, k=SPRING_CONST, method="aseneb")
    _restart_phase = 2
else:
    images = [is_end] + [is_raw.copy() for _ in range(N_IMAGES)] + [fs_end]
    neb = NEB(images, climb=False, k=SPRING_CONST, method="aseneb")
    neb.interpolate(method="idpp")
    print("IDPP interpolation done")
    sys.stdout.flush()
    for img in images[1:-1]:
        img.calc = make_calc()
    _restart_phase = 1

# ── Phase 1: regular NEB (skipped on restart) ─────────────────────
if _restart_phase == 1:
    print(f"\nPhase 1: regular NEB  ({N1_STEPS} steps, fmax={N1_FMAX:.3f} eV/Å)")
    sys.stdout.flush()
    _traj1_kw = {"trajectory": TRAJ_PHASE1} if TRAJ_PHASE1 else {}
    opt1 = MDMin(neb, logfile=LOG_PHASE1, dt=0.05, **_traj1_kw)
    opt1.run(fmax=N1_FMAX, steps=N1_STEPS)
    print(f"Phase 1 done: {opt1.nsteps} steps")
    sys.stdout.flush()

    if TRAJ_PHASE1 and os.path.exists(TRAJ_PHASE1):
        from ase.io import read as _r1, write as _w1
        _lmp1 = TRAJ_PHASE1.replace(".traj", ".extxyz")
        _w1(_lmp1, _r1(TRAJ_PHASE1, index=":"), format="extxyz")
        print(f"Wrote OVITO trajectory: {_lmp1}")
        sys.stdout.flush()

    for img in images[1:-1]:
        img.set_momenta(np.zeros_like(img.get_momenta()))

# ── Phase 2: CINEB ────────────────────────────────────────────────
neb.climb = True
print(f"\nPhase 2: CINEB  ({NEB_STEPS} steps, fmax={NEB_FMAX:.3f} eV/Å)")
sys.stdout.flush()
_traj2_kw = {"trajectory": TRAJ_PHASE2} if TRAJ_PHASE2 else {}
opt2 = MDMin(neb, logfile=LOG_PHASE2, dt=0.02, **_traj2_kw)
converged = False
try:
    converged = opt2.run(fmax=NEB_FMAX, steps=NEB_STEPS)
except Exception as exc:
    print(f"WARNING: phase 2 raised: {exc}")
    sys.stdout.flush()
print(f"Phase 2 done: {opt2.nsteps} steps")
sys.stdout.flush()

if TRAJ_PHASE2 and os.path.exists(TRAJ_PHASE2):
    from ase.io import read as _r2, write as _w2
    _lmp2 = TRAJ_PHASE2.replace(".traj", ".extxyz")
    _w2(_lmp2, _r2(TRAJ_PHASE2, index=":"), format="extxyz")
    print(f"Wrote OVITO trajectory: {_lmp2}")
    sys.stdout.flush()

# ── Extract MEP results ───────────────────────────────────────────
energies = []
for img in images:
    try:    energies.append(img.get_potential_energy())
    except: energies.append(None)

valid  = [e for e in energies if e is not None]
e_ts   = max(valid)
E_abs  = e_ts  - E_IS
E_des  = e_ts  - E_FS
dE     = E_FS  - E_IS

fmax_vals = []
for img in images[1:-1]:
    try:
        f = img.get_forces()
        fmax_vals.append(float(np.sqrt((f**2).sum(axis=1).max())))
    except Exception:
        pass
fmax_final = max(fmax_vals) if fmax_vals else float("nan")

print(f"\nResults")
print(f"  E_IS    : {E_IS:.6f} eV")
print(f"  E_FS    : {E_FS:.6f} eV")
print(f"  E_abs   : {E_abs:.4f} eV")
print(f"  E_des   : {E_des:.4f} eV")
print(f"  delta_E : {dE:.4f} eV")
print(f"  fmax    : {fmax_final:.4f} eV/Å")
print(f"  Converged: {converged}")
sys.stdout.flush()

# ── Write output files ────────────────────────────────────────────
os.makedirs(os.path.dirname(BARRIER_FILE) or ".", exist_ok=True)
os.makedirs(os.path.dirname(PATH_FILE) or ".", exist_ok=True)

n = len(energies)
with open(BARRIER_FILE, "w", encoding="utf-8") as f:
    f.write(f"IS          : {LABEL_IS}\n")
    f.write(f"FS          : {LABEL_FS}\n")
    f.write(f"N images    : {n} ({n-2} intermediate + IS + FS)\n")
    f.write(f"fmax_final  : {fmax_final:.4f} eV/A\n")
    f.write(f"Converged   : {converged}\n\n")
    f.write(f"E_IS    = {E_IS:.6f} eV\n")
    f.write(f"E_FS    = {E_FS:.6f} eV\n")
    f.write(f"E_abs   = {E_abs:.4f} eV\n")
    f.write(f"E_des   = {E_des:.4f} eV\n")
    f.write(f"delta_E = {dE:.4f} eV\n\n")
    f.write("Image energies:\n")
    for i, e in enumerate(energies):
        lbl = "IS" if i == 0 else ("FS" if i == n-1 else f"img_{i}")
        if e is not None:
            f.write(f"  {lbl:6s}: {e:.6f} eV  ({e-E_IS:+.4f} eV)\n")

with open(PATH_FILE, "w", encoding="utf-8") as f:
    f.write("# image_frac  E_eV  dE_from_IS_eV\n")
    for i, e in enumerate(energies):
        if e is not None:
            f.write(f"{i/(n-1):.4f}  {e:.6f}  {e-E_IS:+.4f}\n")

print(f"Wrote: {BARRIER_FILE}")
print(f"Wrote: {PATH_FILE}")

# ── Write per-image LAMMPS data files ─────────────────────────────
os.makedirs(IMAGES_DIR, exist_ok=True)
from ase.io import write as _ase_write
_n = len(images)
for _i, _img in enumerate(images):
    _lbl  = "IS" if _i == 0 else ("FS" if _i == _n - 1 else f"img_{_i:02d}")
    _path = os.path.join(IMAGES_DIR, f"image_{_i:02d}_{_lbl}.lammps")
    _ase_write(_path, _img, format="lammps-data", atom_style="atomic")
print(f"Wrote {_n} image structures → {IMAGES_DIR}/")
